// Rich content for every platform/product page. Slug matches Header links.
export type FAQ = { q: string; a: string };
export type WorkflowStep = { title: string; desc: string };
export type ProductContent = {
  slug: string;
  category: string;
  name: string;
  hero: { title: string; subtitle: string };
  metaTitle: string;
  metaDescription: string;
  benefits: string[];
  features: { title: string; desc: string }[];
  workflow: WorkflowStep[];
  useCases: { title: string; desc: string }[];
  integrations: string[];
  dashboard: { title: string; metrics: { label: string; value: string; delta?: string }[] };
  intro: string; // long-form 200+ words
  body: string;  // long-form 250+ words
  faqs: FAQ[];
  related: string[]; // slugs
};

const base = (s: Partial<ProductContent>): ProductContent => ({
  slug: "", category: "Platform", name: "", hero: { title: "", subtitle: "" },
  metaTitle: "", metaDescription: "",
  benefits: [], features: [], workflow: [], useCases: [], integrations: [],
  dashboard: { title: "Live Dashboard", metrics: [] },
  intro: "", body: "", faqs: [], related: [],
  ...s,
});

export const products: ProductContent[] = [
  base({
    slug: "core-hr", category: "Core HR", name: "Core HR",
    hero: { title: "Core HR — One Source of Truth for Every Employee",
      subtitle: "Unified employee data, org charts, document vault and lifecycle workflows for global teams." },
    metaTitle: "Core HR Software — Radix StratEdge People Cloud",
    metaDescription: "Modern Core HR platform with unified employee records, org charts, document management, and lifecycle workflows.",
    benefits: [
      "Single employee record across every module",
      "Drag-and-drop organisational charts",
      "Secure document vault with e-signatures",
      "Configurable lifecycle workflows",
      "Multi-entity, multi-country, multi-currency",
      "Mobile-first employee self-service",
    ],
    features: [
      { title: "Unified Employee Profile", desc: "360° profile combining personal, job, compensation, benefits, documents and history." },
      { title: "Dynamic Org Chart", desc: "Drag-and-drop org design with reporting hierarchies, dotted lines and matrix structures." },
      { title: "Document Vault", desc: "Secure storage with versioning, expiry alerts and e-signature workflows." },
      { title: "Lifecycle Workflows", desc: "Automate confirmations, transfers, promotions, separations and 30+ HR events." },
      { title: "Custom Fields & Forms", desc: "Extend any object with custom fields, sections and validation rules without code." },
      { title: "Multi-Entity Architecture", desc: "Operate hundreds of legal entities with isolated policies, approvals and reporting." },
    ],
    workflow: [
      { title: "Capture", desc: "Onboard from ATS or import existing employees with bulk tools." },
      { title: "Configure", desc: "Define entities, departments, locations, grades and lifecycle workflows." },
      { title: "Automate", desc: "Trigger letters, tasks and approvals on every employee event." },
      { title: "Insight", desc: "Real-time dashboards on headcount, attrition, diversity and cost." },
    ],
    useCases: [
      { title: "Global HQ Rollout", desc: "Unify HR data across 40 countries with localised compliance." },
      { title: "M&A Integration", desc: "Merge acquired entities into a single platform in under 30 days." },
      { title: "Workforce Restructure", desc: "Model org redesign scenarios with cost and span-of-control analysis." },
    ],
    integrations: ["SAP", "Oracle EBS", "Workday", "NetSuite", "Microsoft 365", "Google Workspace", "Slack", "Okta"],
    dashboard: { title: "Workforce Overview", metrics: [
      { label: "Active Employees", value: "12,840", delta: "+3.2%" },
      { label: "Open Positions", value: "184", delta: "+12" },
      { label: "Attrition (TTM)", value: "8.4%", delta: "-1.1%" },
      { label: "Avg Tenure", value: "4.1 yrs", delta: "+0.3" },
    ]},
    intro: "Radix Core HR replaces fragmented spreadsheets, legacy HRIS modules and shadow systems with a single, cloud-native employee record. Every payroll run, performance review, leave request, timesheet and learning activity references the same source of truth — eliminating reconciliation errors and giving HR leaders confidence in every metric they report to the board.",
    body: "Built for enterprises operating across multiple legal entities, currencies and statutory regimes, Radix Core HR ships with pre-configured templates for 50+ countries and the flexibility to model any organisational structure. The platform's metadata-driven architecture lets administrators add custom objects, fields and workflows without engineering effort, ensuring the system evolves as fast as the business. Granular role-based access, field-level masking and a complete immutable audit trail satisfy the most demanding security, privacy and audit requirements — including ISO 27001, SOC 2 Type II, GDPR and India's DPDPA.",
    faqs: [
      { q: "Can Core HR support multiple legal entities?", a: "Yes. Radix supports unlimited legal entities with isolated policies, approval matrices, payroll calendars, statutory codes and reporting — all from a single tenant." },
      { q: "How do you handle data migration?", a: "Our implementation team provides a templated migration framework with validation rules, dry-runs and rollback support. Typical Core HR migrations complete in 4 to 8 weeks." },
      { q: "Is the platform GDPR and DPDPA compliant?", a: "Yes. Radix is ISO 27001, SOC 2 Type II, GDPR and DPDPA aligned with regional data residency options in India, EU, US and APAC." },
      { q: "Can I extend the data model without code?", a: "Absolutely. Administrators can add custom fields, sections, forms, validations and workflow steps to any HR object using a no-code studio." },
    ],
    related: ["payroll-management", "employee-self-service", "performance-management", "employee-onboarding"],
  }),

  base({
    slug: "payroll-management", category: "Core HR", name: "Payroll",
    hero: { title: "Payroll That Runs Itself — Accurate, Compliant, On Time",
      subtitle: "Multi-country payroll with statutory automation, bank file generation and complete audit trails." },
    metaTitle: "Payroll Management Software — Radix StratEdge",
    metaDescription: "Automated multi-country payroll with statutory compliance, bank integration and audit-ready reporting.",
    benefits: [
      "99.99% calculation accuracy",
      "Statutory compliance for 50+ countries",
      "Bank-ready transfer files in seconds",
      "Flexible Benefits Plan (FBP)",
      "Full-and-final settlement automation",
      "Real-time payroll cost dashboards",
    ],
    features: [
      { title: "Multi-Country Engine", desc: "Run payroll for IN, US, UK, SG, AE, AU and 50+ countries with localised tax engines." },
      { title: "Statutory Automation", desc: "PF, ESI, PT, TDS, LWF, Gratuity, 401(k), PAYE, CPF and more — auto-calculated and filed." },
      { title: "Bank Integration", desc: "Generate NEFT, ACH, SEPA, FAST files for 200+ banks with reconciliation." },
      { title: "Reimbursements & FBP", desc: "Configurable FBP with receipt OCR, approvals and tax-optimised payouts." },
      { title: "Loans & Advances", desc: "Multi-instalment loans with interest, prepayment and payslip integration." },
      { title: "Audit Trail", desc: "Every change, override and approval logged with user, timestamp and reason." },
    ],
    workflow: [
      { title: "Inputs", desc: "Attendance, leave, variable pay and one-time payments auto-flow from connected modules." },
      { title: "Calculate", desc: "Run a payroll preview with full breakdown and variance analysis vs prior period." },
      { title: "Approve", desc: "Multi-level approval with digital sign-off and exception handling." },
      { title: "Disburse", desc: "Generate bank files, payslips, statutory challans and journal vouchers." },
    ],
    useCases: [
      { title: "Multi-Country Enterprise", desc: "Run a unified payroll calendar across 40 countries with local compliance." },
      { title: "High-Volume Contract Workforce", desc: "Process 50,000+ contract workers per cycle with daily-wage support." },
      { title: "M&A Day-1 Payroll", desc: "Onboard an acquired entity onto Radix payroll in under 30 days." },
    ],
    integrations: ["Tally", "SAP FI", "NetSuite", "QuickBooks", "Zoho Books", "ICICI", "HDFC", "Citi"],
    dashboard: { title: "Payroll Run — November 2025", metrics: [
      { label: "Gross Payout", value: "₹18.4 Cr", delta: "+2.1%" },
      { label: "Employees Paid", value: "12,840" },
      { label: "Variance vs Prior", value: "+₹38 L", delta: "+2.1%" },
      { label: "Statutory Liability", value: "₹2.6 Cr" },
    ]},
    intro: "Radix Payroll eliminates the spreadsheet nightmare of multi-country, multi-entity pay runs. Pre-built statutory engines, configurable salary structures and a fully audited workflow let payroll teams close cycles in hours instead of days — with the accuracy and compliance that finance, audit and the workforce all demand.",
    body: "The platform calculates statutory deductions, generates challans and files returns for PF, ESI, PT, TDS, LWF and Gratuity in India, plus equivalent obligations across 50+ countries. Salary structures are fully configurable with formulas, eligibility rules and effective-dated changes. Variable pay, incentives, loans, advances and Flexible Benefits Plan submissions integrate seamlessly — every input is captured with an audit trail. Approval workflows enforce segregation of duties, and a real-time variance dashboard surfaces anomalies before disbursement. Bank files are generated for 200+ banks worldwide, with automatic reconciliation against the GL.",
    faqs: [
      { q: "Which Indian statutory compliances are supported?", a: "PF, ESI, PT (all states), TDS, LWF, Gratuity, Bonus Act, Form 16, Form 24Q, Form 12BA, ECR generation and Shops & Establishments." },
      { q: "Can salary structures be employee-specific?", a: "Yes. Create unlimited salary structures with formulas, eligibility rules, effective-dated changes and grandfathering." },
      { q: "How accurate are payroll calculations?", a: "Radix maintains 99.99% calculation accuracy across customer payrolls processing over 5 million payslips monthly, backed by an SLA." },
      { q: "Do you support shadow payroll for expatriates?", a: "Yes. Radix supports shadow payroll, hypo-tax, tax-equalisation and split-payroll scenarios for global mobility." },
    ],
    related: ["core-hr", "attendance-management", "leave-management", "workforce-analytics"],
  }),

  base({
    slug: "attendance-management", category: "Core HR", name: "Attendance",
    hero: { title: "Attendance, Reimagined for the Modern Workforce",
      subtitle: "Geo-fencing, biometric, web, mobile and shift-aware attendance with real-time compliance." },
    metaTitle: "Attendance Management Software — Radix StratEdge",
    metaDescription: "Cloud attendance with geo-fencing, biometric, mobile selfie and shift-aware capture for distributed workforces.",
    benefits: [
      "5+ capture modes (web, mobile, biometric, RFID, geo)",
      "Real-time exception alerts",
      "Auto-regularisation rules",
      "Shift, weekly-off and roster aware",
      "Offline mobile capture",
      "Direct payroll integration",
    ],
    features: [
      { title: "Geo-Fenced Capture", desc: "Define geo-fences for sites with selfie verification, GPS spoof detection and offline mode." },
      { title: "Biometric & RFID", desc: "Integrate with 50+ device brands — face, fingerprint, RFID and turnstiles." },
      { title: "Smart Shift Engine", desc: "Auto-assign shifts based on rosters, swaps, overtime and rest-period rules." },
      { title: "Exception Workflows", desc: "Tardiness, missed punches and overtime trigger configurable approval flows." },
      { title: "Overtime & Comp-Off", desc: "Policy-driven OT calculation with comp-off credits and statutory limits." },
      { title: "Real-Time Dashboards", desc: "Live floor utilisation, absenteeism and shift coverage across every site." },
    ],
    workflow: [
      { title: "Capture", desc: "Employees punch via web, mobile, biometric or RFID — even offline." },
      { title: "Validate", desc: "Geo-fence, IP, device, photo and shift checks happen automatically." },
      { title: "Regularise", desc: "Exceptions route to managers with single-click approve, reject or edit." },
      { title: "Process", desc: "Attendance flows into payroll, leave and analytics without manual export." },
    ],
    useCases: [
      { title: "Distributed Sales Teams", desc: "Geo-fenced mobile capture with offline support for field reps." },
      { title: "Plant & Warehouse", desc: "Biometric and RFID at gates with shift-aware overtime calculations." },
      { title: "Hybrid Office", desc: "Web check-in with desk booking and IP-based validation." },
    ],
    integrations: ["eSSL", "Matrix", "ZKTeco", "Suprema", "Microsoft Teams", "Slack"],
    dashboard: { title: "Today — Live Attendance", metrics: [
      { label: "Present", value: "11,420", delta: "94%" },
      { label: "On Leave", value: "612" },
      { label: "Late Arrivals", value: "184" },
      { label: "OT Hours", value: "1,840" },
    ]},
    intro: "Modern workforces are mobile, hybrid, shift-based and spread across hundreds of sites. Radix Attendance unifies every capture mode — web, mobile, geo-fenced selfie, biometric, RFID — into a single shift-aware engine that feeds payroll, compliance and analytics in real time.",
    body: "Attendance rules are codified in policies that handle shifts, rosters, swaps, overtime limits, statutory rest periods and weekly-off compensation. Mobile capture works offline with periodic background sync and tamper detection. Biometric integrations cover 50+ device brands across face, fingerprint and RFID, with automatic device-health monitoring. Exception workflows route tardiness, missed punches and OT requests to the right manager with single-click approvals. Every transaction is logged for audit, and downstream systems — payroll, leave, analytics — consume validated attendance data without manual export.",
    faqs: [
      { q: "Does mobile attendance work offline?", a: "Yes. Punches are stored locally with tamper-evident hashing and sync when connectivity returns." },
      { q: "Which biometric devices are supported?", a: "50+ models from eSSL, Matrix, ZKTeco, Suprema, Realtime, Hikvision and more — including face, fingerprint and RFID." },
      { q: "Can I prevent GPS spoofing on mobile?", a: "Yes. Radix detects mock-location apps, rooted devices, emulators and inconsistent telemetry and flags suspicious punches." },
      { q: "How does overtime calculation work?", a: "OT is policy-driven by site, grade or contract — supporting daily, weekly, statutory thresholds and comp-off credits." },
    ],
    related: ["leave-management", "shift-management", "payroll-management", "geo-fencing"],
  }),

  base({
    slug: "leave-management", category: "Core HR", name: "Leave Management",
    hero: { title: "Leave Management for Any Policy, Any Geography",
      subtitle: "Configurable leave policies, balances, accruals and approvals — automated for every employee." },
    metaTitle: "Leave Management Software — Radix StratEdge",
    metaDescription: "Configurable leave policies, accruals, carry-forward, encashment and approval workflows for global enterprises.",
    benefits: ["Unlimited leave types and policies", "Auto-accruals and carry-forward", "Holiday calendars by location", "Multi-level approval chains", "Leave encashment and lapse rules", "Calendar and Slack integrations"],
    features: [
      { title: "Policy Builder", desc: "Configure any leave type with accrual rules, eligibility, caps and lapse logic." },
      { title: "Holiday Calendars", desc: "Maintain unique holiday calendars per location, entity or employee group." },
      { title: "Approval Workflows", desc: "Sequential, parallel or matrix approvals with auto-escalation and delegation." },
      { title: "Encashment & Carry-Forward", desc: "Policy-driven year-end processing with payroll handoff." },
      { title: "Team Calendar", desc: "Manager view of team availability with conflict detection and planning." },
      { title: "Compensatory Off", desc: "Auto-credit comp-off from attendance with expiry tracking." },
    ],
    workflow: [
      { title: "Apply", desc: "Employees apply from web, mobile or Slack with auto-balance check." },
      { title: "Approve", desc: "Managers approve in one click with full context and team coverage view." },
      { title: "Process", desc: "Balances update instantly and flow to payroll, attendance and analytics." },
      { title: "Year-End", desc: "Auto-run carry-forward, encashment and lapse with audit trail." },
    ],
    useCases: [
      { title: "Multi-Country Holidays", desc: "Run unique holiday calendars across 40 locations with auto-application." },
      { title: "Maternity & Long Leave", desc: "Configure parental, sabbatical and statutory leave with payroll integration." },
      { title: "Encashment at FnF", desc: "Automate leave encashment during full-and-final settlement." },
    ],
    integrations: ["Outlook", "Google Calendar", "Slack", "Microsoft Teams"],
    dashboard: { title: "Leave Overview", metrics: [
      { label: "Pending Approvals", value: "62" },
      { label: "Avg Balance", value: "11.4 days" },
      { label: "On Leave Today", value: "612" },
      { label: "FY Encashment", value: "₹14 L" },
    ]},
    intro: "Radix Leave Management handles every leave policy an enterprise can throw at it — annual, sick, casual, parental, sabbatical, comp-off, statutory and bespoke — with automatic accruals, carry-forward, encashment and lapse processing across multiple geographies.",
    body: "Administrators build policies in a no-code studio with rules for eligibility, accrual frequency, caps, prorations and lapse. Approval workflows can be sequential, parallel or matrix-based with delegation and auto-escalation when SLAs are missed. Employees apply via web, mobile or Slack with real-time balance checks and conflict detection against team calendars. Year-end processing — carry-forward, encashment, lapse — runs automatically with payroll integration and a complete audit trail.",
    faqs: [
      { q: "Can I configure custom leave types?", a: "Yes. Create unlimited leave types with bespoke accrual, eligibility, approval and lapse rules." },
      { q: "Do you integrate with Outlook and Google Calendar?", a: "Yes. Approved leaves auto-sync to personal and team calendars with two-way blocking." },
      { q: "How does year-end carry-forward work?", a: "Policies define carry-forward caps, encashment, and lapse rules — Radix runs the year-end job automatically with full audit." },
      { q: "Can employees apply leave from mobile?", a: "Yes. The Radix mobile app supports apply, withdraw, approve and balance check with offline draft." },
    ],
    related: ["attendance-management", "core-hr", "employee-self-service", "payroll-management"],
  }),

  base({
    slug: "employee-self-service", category: "Core HR", name: "Employee Self Service",
    hero: { title: "A Self-Service Experience Employees Actually Love",
      subtitle: "Mobile-first ESS with payslips, leave, attendance, helpdesk, announcements and AI assistant." },
    metaTitle: "Employee Self Service Software — Radix StratEdge",
    metaDescription: "Modern ESS portal and mobile app with payslips, leave, attendance, helpdesk and AI HR assistant.",
    benefits: ["Native iOS & Android apps", "AI HR assistant in chat", "Helpdesk with SLA tracking", "Payslip & tax docs", "Announcements & feed", "Single sign-on"],
    features: [
      { title: "Mobile-First Apps", desc: "Native iOS and Android apps with offline support and biometric login." },
      { title: "AI Assistant", desc: "Conversational HR assistant answers policy, payslip and leave questions instantly." },
      { title: "Helpdesk", desc: "Multi-category tickets with SLA, escalation, CSAT and knowledge base." },
      { title: "Payslip & Tax", desc: "Self-serve payslips, Form 16, tax declarations and investment proofs." },
      { title: "Announcements", desc: "Targeted announcements with reactions, polls and acknowledgement tracking." },
      { title: "Single Sign-On", desc: "SAML/OIDC SSO with Okta, Azure AD, Google and 30+ identity providers." },
    ],
    workflow: [
      { title: "Login", desc: "SSO or biometric login on web and mobile." },
      { title: "Self-Serve", desc: "Apply leave, view payslip, raise tickets, update profile, mark attendance." },
      { title: "Get Help", desc: "Ask the AI assistant or open a ticket — both connected to your data." },
      { title: "Stay Informed", desc: "Personalised feed of announcements, learning, surveys and events." },
    ],
    useCases: [
      { title: "Distributed Frontline", desc: "Mobile-first ESS for store, plant and field workers with low data usage." },
      { title: "Global HQ", desc: "Multi-language ESS with SSO, localised payslips and announcements." },
      { title: "Hybrid Workforce", desc: "Single app for desk booking, hybrid attendance and team coordination." },
    ],
    integrations: ["Okta", "Azure AD", "Google", "Slack", "Microsoft Teams", "WhatsApp"],
    dashboard: { title: "ESS Engagement (30d)", metrics: [
      { label: "DAU", value: "9,840", delta: "+12%" },
      { label: "Tickets Resolved", value: "2,418" },
      { label: "Avg CSAT", value: "4.6 / 5" },
      { label: "AI Assistant Usage", value: "14,200" },
    ]},
    intro: "Radix Employee Self Service turns the daily HR experience from frustrating to delightful. A modern, mobile-first interface — backed by a conversational AI assistant — lets employees handle payslips, leave, attendance, helpdesk, announcements and profile updates without ever opening a ticket.",
    body: "The Radix mobile apps are native, fast and built for low-data environments — ideal for retail, manufacturing and field workforces. SSO with Okta, Azure AD, Google and 30+ identity providers means zero password fatigue. A multi-category helpdesk with SLA tracking, escalation paths and a knowledge base reduces L1 HR effort by 60%+. The built-in AI assistant answers policy questions, generates letters, summarises payslips and walks employees through self-service flows in natural language across English, Hindi and 20+ languages.",
    faqs: [
      { q: "Are the mobile apps native?", a: "Yes. Radix ships native iOS and Android apps with offline support, biometric login and push notifications." },
      { q: "Can the AI assistant be customised?", a: "Yes. Admins train the assistant on company policies, handbook content and SOPs — with role-based access controls." },
      { q: "Which SSO providers are supported?", a: "Okta, Azure AD, Google, OneLogin, JumpCloud and any SAML 2.0 or OIDC compliant provider." },
      { q: "Is the app available in regional languages?", a: "Yes. Radix supports 20+ languages including English, Hindi, Tamil, Telugu, Bengali, Marathi, Spanish and Arabic." },
    ],
    related: ["core-hr", "leave-management", "attendance-management", "payroll-management"],
  }),

  base({
    slug: "applicant-tracking-system", category: "Talent", name: "Applicant Tracking System (ATS)",
    hero: { title: "An AI-Powered ATS Built for Modern Recruiting",
      subtitle: "From requisition to offer — pipelines, AI screening, interview scheduling and analytics." },
    metaTitle: "Applicant Tracking System (ATS) — Radix StratEdge",
    metaDescription: "AI-powered ATS with multi-channel sourcing, resume screening, interview scheduling and offer management.",
    benefits: ["30+ job boards in one click", "AI resume parsing & screening", "Smart interview scheduling", "Branded careers site", "Offer letter automation", "Recruiter productivity analytics"],
    features: [
      { title: "Multi-Channel Sourcing", desc: "Post to 30+ job boards, LinkedIn, employee referrals and agencies in one click." },
      { title: "AI Resume Screening", desc: "GPT-grade resume parsing, JD matching, deduplication and ranking." },
      { title: "Interview Scheduling", desc: "Calendar-aware self-scheduling with panel coordination across time zones." },
      { title: "Careers Site Builder", desc: "Branded, SEO-friendly careers site with content blocks and analytics." },
      { title: "Offer Management", desc: "Templated offer letters with e-signature, salary calculator and approvals." },
      { title: "Recruiter Analytics", desc: "Pipeline velocity, source effectiveness, recruiter load and DEI metrics." },
    ],
    workflow: [
      { title: "Source", desc: "Open requisitions, broadcast to job boards and referrals." },
      { title: "Screen", desc: "AI parses, ranks and shortlists candidates with explainable scoring." },
      { title: "Interview", desc: "Self-scheduling, scorecards and panel feedback in one workspace." },
      { title: "Hire", desc: "Generate offers, capture e-signatures and trigger onboarding." },
    ],
    useCases: [
      { title: "High-Volume Hiring", desc: "Process 50,000+ applications per quarter with AI shortlisting." },
      { title: "Niche Tech Roles", desc: "Skill-based AI matching and pipeline nurturing for hard-to-fill roles." },
      { title: "Campus Drives", desc: "End-to-end campus engagement with assessments and bulk offers." },
    ],
    integrations: ["LinkedIn", "Naukri", "Indeed", "Glassdoor", "HackerRank", "Codility", "DocuSign", "Zoom"],
    dashboard: { title: "Hiring Pipeline — Q4", metrics: [
      { label: "Open Roles", value: "184" },
      { label: "Applications", value: "14,820", delta: "+22%" },
      { label: "Time-to-Hire", value: "26 days", delta: "-6 days" },
      { label: "Offer Accept", value: "89%" },
    ]},
    intro: "Radix ATS is built for recruiting teams that hire at scale without sacrificing candidate experience. A unified workspace combines sourcing, screening, scheduling, assessments and offer management — with AI woven through every step to amplify recruiter productivity.",
    body: "Multi-channel sourcing reaches 30+ job boards, premium networks, employee referrals and agency portals in one click. AI resume parsing extracts structured data with 95%+ accuracy, while explainable screening models rank candidates against requisition requirements and surface diversity considerations. Self-scheduling eliminates email tag — candidates pick from real-time interviewer availability across panels and time zones. Branded careers sites are built with drag-and-drop blocks and optimised for SEO. Offer management includes salary calculators, approval matrices, e-signatures and seamless handoff to onboarding.",
    faqs: [
      { q: "How accurate is the AI resume parser?", a: "Radix AI parser achieves 95%+ accuracy across English, Hindi and 15+ languages with explainable confidence scores." },
      { q: "Can I build a branded careers site?", a: "Yes. The drag-and-drop builder creates fast, SEO-friendly careers sites with custom domains, analytics and accessibility compliance." },
      { q: "Does the ATS integrate with assessment platforms?", a: "Yes — HackerRank, Codility, iMocha, Mettl and custom assessment platforms via webhooks." },
      { q: "How is candidate data protected?", a: "Encryption at rest and in transit, role-based access, candidate data residency options, and GDPR/DPDPA consent workflows." },
    ],
    related: ["employee-onboarding", "core-hr", "performance-management", "people-analytics"],
  }),

  base({
    slug: "employee-onboarding", category: "Talent", name: "Onboarding",
    hero: { title: "Onboarding Journeys From Offer to Day-90",
      subtitle: "Pre-boarding, document collection, e-signatures, IT provisioning and structured 30-60-90 plans." },
    metaTitle: "Employee Onboarding Software — Radix StratEdge",
    metaDescription: "Automated employee onboarding with document collection, e-signatures, IT provisioning and structured 30-60-90 plans.",
    benefits: ["Branded pre-boarding portal", "Automated document collection", "E-signature workflows", "IT & asset provisioning", "Buddy & mentor matching", "30-60-90 day journey tracking"],
    features: [
      { title: "Pre-Boarding Portal", desc: "Branded portal where new hires sign documents, upload IDs and meet their team." },
      { title: "Document Collection", desc: "OCR-driven KYC, BGV trigger and statutory document compliance." },
      { title: "IT Provisioning", desc: "Trigger laptop, badge, software and access provisioning via integrations." },
      { title: "Buddy & Mentor", desc: "Auto-match new hires with buddies and mentors based on team and role." },
      { title: "30-60-90 Plan", desc: "Structured journey with tasks, learning, check-ins and feedback surveys." },
      { title: "Manager Cockpit", desc: "Single view for managers to track every new hire's progress and risks." },
    ],
    workflow: [
      { title: "Offer Accepted", desc: "Pre-boarding portal goes live with personalised checklist and welcome content." },
      { title: "Day -7 to Day 0", desc: "Documents signed, BGV completed, IT assets dispatched, buddy assigned." },
      { title: "Day 1 to Day 30", desc: "Structured orientation, learning paths and team integration." },
      { title: "Day 60 to Day 90", desc: "Check-ins, manager feedback, role-fit survey and probation review." },
    ],
    useCases: [
      { title: "Remote Onboarding", desc: "Fully digital onboarding with virtual buddy matching and async learning." },
      { title: "High-Volume Joiners", desc: "Onboard 1,000+ campus hires in a week with templated journeys." },
      { title: "Executive Onboarding", desc: "White-glove journey with stakeholder mapping and 90-day plan." },
    ],
    integrations: ["DocuSign", "Adobe Sign", "Jira", "ServiceNow", "Okta", "Slack", "Microsoft Teams"],
    dashboard: { title: "Onboarding in Progress", metrics: [
      { label: "In Pipeline", value: "84" },
      { label: "Avg Time-to-Productivity", value: "42 days", delta: "-8 days" },
      { label: "30-day Survey", value: "4.5 / 5" },
      { label: "BGV Pending", value: "6" },
    ]},
    intro: "First impressions matter. Radix Onboarding turns offer-letter acceptance into a structured, engaging journey that has new hires productive in weeks — not months — while removing the manual coordination that drains HR and IT teams.",
    body: "From the moment a candidate accepts, a branded pre-boarding portal welcomes them with personalised content, documents, buddies and a glimpse of their team. Document collection is OCR-driven with automatic statutory validation. BGV workflows trigger third-party checks and surface red flags before Day 1. IT and asset provisioning happens via integrations with Jira, ServiceNow, Okta and your MDM. Structured 30-60-90 day journeys assign tasks, learning paths, mentor sessions and pulse surveys — giving managers a single cockpit to spot risks and celebrate wins.",
    faqs: [
      { q: "Can onboarding journeys be role-specific?", a: "Yes. Create unlimited templates by role, level, location or business unit with conditional tasks." },
      { q: "Does Radix support background verification?", a: "Yes. Pre-integrated with leading BGV vendors with automated triggers, status tracking and red-flag alerts." },
      { q: "How are IT assets provisioned?", a: "Integrations with Jira, ServiceNow, Okta and MDM platforms trigger laptop, badge, software and access provisioning automatically." },
      { q: "Can managers track new-hire progress?", a: "Yes. The manager cockpit shows journey progress, pending tasks, feedback scores and risks for every new hire." },
    ],
    related: ["applicant-tracking-system", "core-hr", "performance-management", "learning-management-system"],
  }),

  base({
    slug: "performance-management", category: "Talent", name: "Performance Management",
    hero: { title: "Continuous Performance, OKRs and 360° Feedback",
      subtitle: "A modern performance system that ties goals, feedback, reviews and growth to business outcomes." },
    metaTitle: "Performance Management Software — Radix StratEdge",
    metaDescription: "OKRs, continuous feedback, 360° reviews, calibration and growth planning in one performance platform.",
    benefits: ["OKR cascading from company to individual", "Continuous feedback culture", "360° reviews with calibration", "AI-driven feedback summarisation", "Manager 1:1 templates", "Promotion and PIP workflows"],
    features: [
      { title: "OKRs & Goals", desc: "Cascade OKRs from company to team to individual with dependencies and check-ins." },
      { title: "Continuous Feedback", desc: "Real-time praise, requested feedback and nudges across the team." },
      { title: "360° Reviews", desc: "Self, manager, peer, direct-report and stakeholder reviews with weighting." },
      { title: "Calibration", desc: "Manager calibration sessions with rating distributions and bias flags." },
      { title: "1:1s & Check-ins", desc: "Structured 1:1 agendas, action items and recurring check-ins." },
      { title: "Growth Plans", desc: "Tie goals to learning, mentors and stretch assignments." },
    ],
    workflow: [
      { title: "Set", desc: "Cascade OKRs and goals from strategy to every individual." },
      { title: "Track", desc: "Weekly check-ins, real-time progress and feedback loops." },
      { title: "Review", desc: "360° reviews with self, manager, peer and stakeholder inputs." },
      { title: "Grow", desc: "Calibrate ratings, plan promotions, build IDPs and trigger learning." },
    ],
    useCases: [
      { title: "OKR Rollout", desc: "Roll out OKRs across 10,000+ employees with cascading visibility." },
      { title: "Annual + Continuous", desc: "Run an annual cycle with monthly check-ins and quarterly feedback." },
      { title: "Promotion Cycles", desc: "Templated promotion packets with calibration and approval workflows." },
    ],
    integrations: ["Slack", "Microsoft Teams", "Notion", "Jira", "Asana"],
    dashboard: { title: "Performance Health", metrics: [
      { label: "OKR Coverage", value: "94%" },
      { label: "Feedback (30d)", value: "4,820" },
      { label: "1:1 Completion", value: "91%" },
      { label: "At-Risk Goals", value: "184" },
    ]},
    intro: "Radix Performance Management replaces the annual-review charade with a continuous performance system that aligns strategy to execution, builds a feedback culture and gives every employee a clear line of sight to their growth.",
    body: "OKRs cascade from company to team to individual with dependency tracking and weekly check-ins. Continuous feedback — praise, requested, anonymous — flows across the team and surfaces in reviews. 360° reviews collect self, manager, peer, direct-report and stakeholder inputs with configurable weighting. AI summarises feedback, highlights themes and flags potential bias. Calibration sessions standardise ratings across managers with distribution analytics. Promotion and PIP workflows automate packets, approvals and downstream actions like comp changes and learning enrolments.",
    faqs: [
      { q: "Do you support OKRs and traditional KPIs?", a: "Yes. Configure goal frameworks per business unit — OKRs, KPIs, MBOs or hybrid models — with full cascading and tracking." },
      { q: "How does 360° feedback work?", a: "Configure 360° cycles with self, manager, peer, direct-report and stakeholder inputs, anonymity controls and weighting." },
      { q: "Can the AI detect bias in reviews?", a: "Yes. Radix AI surfaces language bias, recency bias and rating-distribution anomalies during calibration." },
      { q: "Does Radix support PIPs?", a: "Yes. Templated PIP workflows with milestones, check-ins, evidence capture and outcome tracking." },
    ],
    related: ["learning-management-system", "people-analytics", "career-development", "core-hr"],
  }),

  base({
    slug: "career-development", category: "Talent", name: "Career Development",
    hero: { title: "Career Paths, Succession and Internal Mobility",
      subtitle: "Map skills, design career paths, identify successors and unlock internal mobility." },
    metaTitle: "Career Development Software — Radix StratEdge",
    metaDescription: "Skills, career paths, succession planning and internal mobility for modern enterprises.",
    benefits: ["Skill taxonomy & gap analysis", "Visual career paths", "Succession planning", "Internal mobility marketplace", "Mentor matching", "Individual Development Plans"],
    features: [
      { title: "Skill Cloud", desc: "AI-extracted skill taxonomy across roles, projects and learning history." },
      { title: "Career Paths", desc: "Visual paths with capability requirements and example trajectories." },
      { title: "Succession Planning", desc: "9-box grids, successor pools, readiness and risk analysis." },
      { title: "Internal Marketplace", desc: "Match employees to gigs, stretch roles and open positions internally." },
      { title: "Mentor Matching", desc: "Smart mentor and mentee pairing across geographies and functions." },
      { title: "IDPs", desc: "Personalised IDPs linked to learning, mentors and stretch assignments." },
    ],
    workflow: [
      { title: "Map", desc: "AI extracts skills from roles, projects, reviews and learning." },
      { title: "Plan", desc: "Visualise paths, design IDPs and identify successors." },
      { title: "Match", desc: "Surface internal gigs, mentors and roles for every employee." },
      { title: "Grow", desc: "Track readiness, close gaps and accelerate mobility." },
    ],
    useCases: [
      { title: "Tech Career Ladders", desc: "Design IC and manager tracks with capability rubrics." },
      { title: "Leadership Succession", desc: "Identify successors for critical roles with risk and readiness." },
      { title: "Internal Mobility", desc: "Fill 30%+ of roles internally with the marketplace." },
    ],
    integrations: ["LinkedIn Learning", "Coursera", "Udemy Business", "Workday"],
    dashboard: { title: "Career Health", metrics: [
      { label: "Skills Captured", value: "184K" },
      { label: "IDPs Active", value: "8,420" },
      { label: "Internal Hires", value: "32%" },
      { label: "Succession Coverage", value: "78%" },
    ]},
    intro: "Radix Career Development turns the abstract idea of growth into a concrete, AI-powered experience. Every employee sees the skills they have, the skills they need and the path to get there — while leaders gain real-time visibility into talent risk and succession readiness.",
    body: "An AI-built skill cloud extracts capabilities from roles, projects, reviews and learning history. Visual career paths show progression with capability requirements. Succession planning combines 9-box grids, successor pools, readiness scores and risk analysis. The internal mobility marketplace matches employees to gigs, stretch roles and open positions, helping enterprises fill 30%+ of roles internally. Mentor matching, IDPs and growth nudges round out a holistic development experience.",
    faqs: [
      { q: "How is the skill taxonomy built?", a: "AI extracts skills from job descriptions, projects, reviews and learning history — admins curate and approve before publishing." },
      { q: "Can I run formal succession reviews?", a: "Yes. Run quarterly or annual succession reviews with 9-box, talent reviews, calibration and risk analysis." },
      { q: "How does the internal marketplace work?", a: "Employees browse internal gigs, projects and roles. AI surfaces best-fit matches based on skills, goals and history." },
      { q: "Does it integrate with our LMS?", a: "Yes. IDPs trigger learning enrolments in Radix LMS or external platforms like LinkedIn Learning, Coursera and Udemy Business." },
    ],
    related: ["performance-management", "learning-management-system", "people-analytics", "workforce-planning"],
  }),

  base({
    slug: "timesheet-management", category: "Workforce", name: "Timesheet Management",
    hero: { title: "Timesheets That Project, Finance and Employees Actually Use",
      subtitle: "Project, client and billable hours with approvals, costing and invoicing-ready exports." },
    metaTitle: "Timesheet Management Software — Radix StratEdge",
    metaDescription: "Project, client and billable timesheets with approvals, costing, utilisation analytics and invoicing exports.",
    benefits: ["Project, client and task tracking", "Billable & non-billable hours", "Approval workflows", "Utilisation analytics", "Cost & revenue dashboards", "Invoice-ready exports"],
    features: [
      { title: "Project & Task Tracking", desc: "Track hours by project, phase, task and client with budgets and milestones." },
      { title: "Billable Hours", desc: "Configure billable rules, rates, multipliers and overtime per project." },
      { title: "Approvals", desc: "Multi-level approvals with budget alerts and exception handling." },
      { title: "Utilisation Analytics", desc: "Real-time dashboards on utilisation, realisation and billable mix." },
      { title: "Cost & Revenue", desc: "Auto-calc loaded cost and project revenue with margin tracking." },
      { title: "Invoicing Exports", desc: "Approved timesheets export to QuickBooks, NetSuite, Tally or CSV." },
    ],
    workflow: [
      { title: "Capture", desc: "Employees log time daily or weekly via web, mobile or Slack." },
      { title: "Approve", desc: "Project managers approve, edit or reject with full context." },
      { title: "Cost", desc: "Loaded cost and revenue calculated and posted to GL." },
      { title: "Bill", desc: "Approved hours export to invoicing or finance systems." },
    ],
    useCases: [
      { title: "IT Services", desc: "Track billable hours across 1,000+ projects with client invoicing." },
      { title: "Consulting", desc: "Manage utilisation, realisation and project margin in real time." },
      { title: "R&D Cost Allocation", desc: "Allocate engineering time to projects for capitalisation." },
    ],
    integrations: ["Jira", "Asana", "QuickBooks", "NetSuite", "Tally", "Microsoft Project"],
    dashboard: { title: "Utilisation — This Month", metrics: [
      { label: "Avg Utilisation", value: "78%", delta: "+3%" },
      { label: "Billable Hours", value: "1.2M" },
      { label: "Active Projects", value: "1,418" },
      { label: "At-Risk Projects", value: "42" },
    ]},
    intro: "Radix Timesheet Management turns time tracking from an administrative chore into a strategic asset. Real-time visibility into utilisation, billable mix and project margin lets services businesses optimise staffing, billing and profitability — without compliance gaps.",
    body: "Employees log time daily or weekly via web, mobile or Slack with project, task and notes. Configurable billing rules handle rates, multipliers, overtime and discounts per client. Approval workflows route to project managers, account leads and finance with budget alerts. Loaded cost and project revenue auto-calculate and post to the GL. Real-time utilisation dashboards surface bench, over-utilisation and billable mix. Approved hours export to QuickBooks, NetSuite, Tally and any invoicing system.",
    faqs: [
      { q: "Can I track multiple billing rates per employee?", a: "Yes. Configure rates by project, client, role and grade with effective-dated changes." },
      { q: "Does Radix integrate with Jira?", a: "Yes. Time logged in Jira syncs to Radix timesheets with project mapping." },
      { q: "Can I forecast utilisation?", a: "Yes. Combine timesheet history with planned allocations for forward-looking utilisation forecasts." },
      { q: "Is mobile time tracking supported?", a: "Yes. Native iOS and Android apps with offline support and timer-based capture." },
    ],
    related: ["workforce-planning", "shift-management", "workforce-analytics", "core-hr"],
  }),

  base({
    slug: "shift-management", category: "Workforce", name: "Shift Management",
    hero: { title: "Shift Rosters & Auto-Scheduling at Scale",
      subtitle: "Build, publish and optimise shift rosters across hundreds of sites with rule-driven auto-scheduling." },
    metaTitle: "Shift Management Software — Radix StratEdge",
    metaDescription: "Shift rosters, auto-scheduling, swaps and statutory compliance for retail, manufacturing and healthcare.",
    benefits: ["Rule-driven auto-scheduling", "Shift swaps & open shifts", "Demand forecasting", "Skill & certification matching", "Statutory rest period compliance", "Mobile roster app"],
    features: [
      { title: "Auto-Scheduler", desc: "Constraint-based engine builds rosters from demand, skills and rules in minutes." },
      { title: "Shift Swaps", desc: "Employees swap shifts with rule-enforced manager approval and audit trail." },
      { title: "Open Shifts", desc: "Publish open shifts to qualified employees with first-come or bid-based fulfilment." },
      { title: "Demand Forecasting", desc: "ML-driven demand forecasts inform staffing levels per site and time-slot." },
      { title: "Compliance Engine", desc: "Statutory rest periods, max hours and union rules enforced automatically." },
      { title: "Mobile Roster", desc: "Employees view, swap and clock-in against shifts from the mobile app." },
    ],
    workflow: [
      { title: "Forecast", desc: "Demand patterns drive shift coverage needs per site and slot." },
      { title: "Build", desc: "Auto-scheduler builds compliant rosters in minutes." },
      { title: "Publish", desc: "Employees view rosters in mobile with swaps and open shifts." },
      { title: "Operate", desc: "Real-time coverage dashboards across every site." },
    ],
    useCases: [
      { title: "Retail Stores", desc: "Roster 50,000+ associates across 1,000 stores with peak-aware coverage." },
      { title: "Hospital Nursing", desc: "Match nurses to shifts by ward, skill and certification with statutory limits." },
      { title: "Plant Operations", desc: "3-shift rosters with overtime, swaps and union compliance." },
    ],
    integrations: ["SAP", "Workday", "Oracle HCM", "ZKTeco"],
    dashboard: { title: "Coverage — Tomorrow", metrics: [
      { label: "Shifts Filled", value: "98.4%" },
      { label: "Open Shifts", value: "62" },
      { label: "Predicted Shortage", value: "4 sites" },
      { label: "OT Hours", value: "1,184" },
    ]},
    intro: "Radix Shift Management replaces spreadsheets and manual rosters with an intelligent scheduling engine that balances demand, skills, compliance and employee preferences at enterprise scale.",
    body: "A constraint-based auto-scheduler builds compliant rosters in minutes — respecting statutory rest periods, max hours, skills, certifications, location preferences and union rules. Demand forecasting uses historical and seasonal patterns to right-size coverage by site and time-slot. Shift swaps and open-shift bidding empower employees and reduce manager load. The mobile app gives employees a single source of truth for their schedule, swaps and clock-in. Coverage dashboards surface gaps before they become incidents.",
    faqs: [
      { q: "How does the auto-scheduler handle constraints?", a: "It uses constraint-programming to satisfy hard rules (rest, max hours, skills) and optimise soft preferences (employee picks, fairness)." },
      { q: "Can employees swap shifts?", a: "Yes. Employees initiate swaps in the mobile app with rule-checked validation and configurable manager approval." },
      { q: "Does it integrate with payroll?", a: "Yes. Shifts feed attendance and overtime directly to Radix Payroll or external payroll systems." },
      { q: "Does it support union compliance?", a: "Yes. Union rules — including max consecutive shifts, mandatory breaks and seniority rules — are codified in the rule engine." },
    ],
    related: ["attendance-management", "workforce-planning", "field-workforce", "geo-fencing"],
  }),

  base({
    slug: "workforce-planning", category: "Workforce", name: "Workforce Planning",
    hero: { title: "Plan Headcount, Cost and Capability — With Confidence",
      subtitle: "Scenario-driven workforce planning that ties strategy to headcount, cost and capability." },
    metaTitle: "Workforce Planning Software — Radix StratEdge",
    metaDescription: "Scenario-based workforce planning for headcount, cost, capability and span-of-control modelling.",
    benefits: ["Multi-scenario modelling", "Headcount & cost forecasting", "Capability gap analysis", "Span-of-control optimisation", "Finance & strategy alignment", "What-if analysis"],
    features: [
      { title: "Scenario Modelling", desc: "Compare multiple workforce plans side-by-side with cost, FTE and capability deltas." },
      { title: "Headcount Forecast", desc: "Roll up org structure into FTE and cost forecasts for the next 1–5 years." },
      { title: "Capability Gaps", desc: "Identify skill gaps that block strategy and plan build-buy-borrow responses." },
      { title: "Span of Control", desc: "Optimise spans, layers and management cost across the org." },
      { title: "Driver-Based Planning", desc: "Tie headcount to revenue, output or capacity drivers." },
      { title: "Finance Integration", desc: "Export plans to financial planning systems with full reconciliation." },
    ],
    workflow: [
      { title: "Baseline", desc: "Start from current org, cost and capability." },
      { title: "Model", desc: "Build multiple scenarios with assumptions and drivers." },
      { title: "Decide", desc: "Compare scenarios with stakeholders and approve the plan." },
      { title: "Execute", desc: "Approved plan flows to hiring, succession and learning." },
    ],
    useCases: [
      { title: "Annual Operating Plan", desc: "Build headcount & cost plans aligned to revenue targets." },
      { title: "Restructure & M&A", desc: "Model org redesign and integration scenarios." },
      { title: "Capability Build", desc: "Plan multi-year skill builds vs hiring vs contracting." },
    ],
    integrations: ["Anaplan", "Workday Adaptive", "Oracle EPM", "Excel"],
    dashboard: { title: "FY26 Plan vs Actual", metrics: [
      { label: "Planned FTE", value: "14,200" },
      { label: "Current FTE", value: "12,840" },
      { label: "Cost Forecast", value: "₹2,140 Cr" },
      { label: "Skill Gaps", value: "184" },
    ]},
    intro: "Radix Workforce Planning gives HR, Finance and Strategy a single source of truth for headcount, cost and capability decisions — replacing email-based spreadsheet chaos with collaborative, scenario-driven modelling.",
    body: "Start from a real-time baseline of org structure, cost and capability. Model multiple scenarios with assumptions and drivers — revenue-linked headcount, capacity-linked staffing, capability ramps. Compare scenarios side-by-side with cost, FTE and capability deltas. Approve the plan and flow it directly to hiring, succession, learning and finance. Continuous re-planning lets you respond to market shifts without starting over.",
    faqs: [
      { q: "Can I run multiple scenarios?", a: "Yes. Compare unlimited scenarios side-by-side with cost, FTE, span and capability deltas." },
      { q: "Does it integrate with FP&A tools?", a: "Yes. Export plans to Anaplan, Workday Adaptive, Oracle EPM, SAP and Excel with full reconciliation." },
      { q: "How is capability data sourced?", a: "Capability data comes from Radix Career Development's skill cloud and external assessments." },
      { q: "Can finance and HR collaborate?", a: "Yes. Multi-user collaboration with comments, approvals and version history keeps everyone aligned." },
    ],
    related: ["people-analytics", "career-development", "workforce-analytics", "core-hr"],
  }),

  base({
    slug: "geo-fencing", category: "Workforce", name: "Geo-Fencing",
    hero: { title: "Geo-Fenced Attendance & Field Verification",
      subtitle: "Location-aware attendance, visit logs and field verification with spoof detection." },
    metaTitle: "Geo-Fencing Attendance Software — Radix StratEdge",
    metaDescription: "Geo-fenced attendance, field visit logs and location verification with GPS spoof detection.",
    benefits: ["Site-level geo-fences", "Selfie & live photo capture", "GPS spoof detection", "Offline punch with sync", "Visit log audit trail", "Battery-efficient SDK"],
    features: [
      { title: "Custom Geo-Fences", desc: "Define geo-fences per site with shape, radius and dwell-time rules." },
      { title: "Selfie Verification", desc: "Face-matched selfie capture with anti-spoof and liveness checks." },
      { title: "Spoof Detection", desc: "Detects mock-location apps, rooted devices and inconsistent telemetry." },
      { title: "Offline Mode", desc: "Punches stored locally and synced when connectivity returns." },
      { title: "Visit Logs", desc: "Field visits with start, route, stops and end with map view." },
      { title: "Privacy Controls", desc: "Granular consent, working-hours-only tracking and data minimisation." },
    ],
    workflow: [
      { title: "Define", desc: "Admin defines geo-fences and rules per site or territory." },
      { title: "Capture", desc: "Employee punches with selfie and GPS — even offline." },
      { title: "Validate", desc: "Geo, device, photo and timing checks happen automatically." },
      { title: "Audit", desc: "All punches and visits stored with full forensic trail." },
    ],
    useCases: [
      { title: "Field Sales", desc: "Verified visits to retail outlets with route history." },
      { title: "Construction Sites", desc: "Site-wise attendance for daily-wage and contract workers." },
      { title: "Last-Mile Delivery", desc: "Driver attendance and stop logs with route playback." },
    ],
    integrations: ["Google Maps", "Mapbox", "OSM"],
    dashboard: { title: "Field Activity — Today", metrics: [
      { label: "Active Field Staff", value: "1,840" },
      { label: "Visits Logged", value: "8,420" },
      { label: "Suspicious Punches", value: "12" },
      { label: "Avg Visit Time", value: "28 min" },
    ]},
    intro: "Radix Geo-Fencing brings rigour and trust to mobile and field workforces. Site-level geo-fences, selfie verification and anti-spoofing combine to give HR and operations the confidence that attendance and visit data is real.",
    body: "Admins define geo-fences per site with custom shapes, radii and dwell-time rules. Employees punch with selfie and GPS — face-matched, liveness-checked and anti-spoofed. Mock-location apps, rooted devices and emulators are detected automatically. The SDK is battery-efficient and works offline with hash-protected local storage. Field visits log routes, stops and dwell times with map playback. Privacy is first-class — granular consent, working-hours-only tracking, and data minimisation align with GDPR and DPDPA.",
    faqs: [
      { q: "How does spoof detection work?", a: "We detect mock-location apps, root/jailbreak, emulators, inconsistent telemetry (GPS vs IP) and impossible-travel patterns." },
      { q: "Does it drain battery?", a: "No. The SDK uses adaptive sampling and significant-location-change APIs — typical impact is under 3% battery per day." },
      { q: "What about privacy concerns?", a: "Granular consent, working-hours-only tracking, data minimisation and user-visible activity logs ensure GDPR/DPDPA alignment." },
      { q: "Can it work offline?", a: "Yes. Punches and visits are stored locally with tamper-evident hashing and synced when connectivity returns." },
    ],
    related: ["attendance-management", "field-workforce", "shift-management", "core-hr"],
  }),

  base({
    slug: "field-workforce", category: "Workforce", name: "Field Workforce",
    hero: { title: "Manage Field Teams With Real-Time Visibility",
      subtitle: "Field attendance, beat plans, visit logs, expense capture and live tracking — purpose-built for mobile workforces." },
    metaTitle: "Field Workforce Management — Radix StratEdge",
    metaDescription: "Field attendance, beat plans, visit logs, expense capture and live tracking for mobile and distributed teams.",
    benefits: ["Beat plans & route optimisation", "Geo-verified visit logs", "Expense capture from mobile", "Live tracking maps", "Daily Sales Reports (DSR)", "Order capture for FMCG"],
    features: [
      { title: "Beat Plans", desc: "Build beat plans by territory with route optimisation and adherence tracking." },
      { title: "Visit Logs", desc: "Geo-verified visit start, in-store time, photos, forms and outcomes." },
      { title: "Live Tracking", desc: "Real-time map of field force with status, last-seen and route history." },
      { title: "Mobile Expense", desc: "Capture expenses on the go with receipt OCR and approval workflows." },
      { title: "DSR Automation", desc: "Auto-generate Daily Sales Reports from visit and order data." },
      { title: "Order Capture", desc: "Capture orders, returns and stock at retail outlets for FMCG and pharma." },
    ],
    workflow: [
      { title: "Plan", desc: "Build beat plans with route optimisation per territory." },
      { title: "Execute", desc: "Field staff follow beats, log visits and capture forms." },
      { title: "Track", desc: "Managers see live status, adherence and outcomes." },
      { title: "Analyse", desc: "Productivity, coverage and conversion dashboards by territory." },
    ],
    useCases: [
      { title: "FMCG Sales", desc: "Beat coverage, order capture and DSR for distributor and modern trade." },
      { title: "Pharma MRs", desc: "Doctor visits, sample capture and call effectiveness tracking." },
      { title: "Insurance Agents", desc: "Lead visits, policy generation and renewal collection." },
    ],
    integrations: ["Google Maps", "Salesforce", "Zoho CRM", "SAP"],
    dashboard: { title: "Field Productivity — This Week", metrics: [
      { label: "Active Reps", value: "1,840" },
      { label: "Visits Completed", value: "42,820", delta: "+8%" },
      { label: "Avg Beat Adherence", value: "84%" },
      { label: "Orders Captured", value: "₹14.2 Cr" },
    ]},
    intro: "Radix Field Workforce gives sales leaders, pharma heads and service heads the real-time visibility they need to run high-performing mobile teams — replacing WhatsApp updates and Excel DSRs with a structured, mobile-first platform.",
    body: "Beat plans are built per territory with route optimisation and adherence tracking. Visit logs are geo-verified with selfies, in-store time, photos, custom forms and outcomes. Managers see live maps of every field rep with status, last-seen, route history and exceptions. Mobile expense capture, DSR automation and order capture round out a complete field workforce platform. Integrations with CRM, ERP and DMS systems mean no double entry.",
    faqs: [
      { q: "Does it support beat plans?", a: "Yes. Build territory-based beats with route optimisation, mandatory stops and adherence tracking." },
      { q: "Can field reps capture orders?", a: "Yes. Capture orders, returns and stock at retail outlets with offline support and CRM/ERP sync." },
      { q: "How is live tracking handled?", a: "Battery-efficient location SDK with adaptive sampling and privacy controls — only tracks during working hours." },
      { q: "Does it work offline?", a: "Yes. Visits, forms, expenses and orders sync when connectivity returns." },
    ],
    related: ["geo-fencing", "attendance-management", "shift-management", "workforce-analytics"],
  }),

  base({
    slug: "workforce-analytics", category: "Analytics", name: "Workforce Analytics",
    hero: { title: "Real-Time Workforce Analytics for Every Leader",
      subtitle: "From CHRO to line manager — pre-built dashboards and a no-code studio for every people decision." },
    metaTitle: "Workforce Analytics Software — Radix StratEdge",
    metaDescription: "Real-time workforce analytics with pre-built dashboards, predictive models and a no-code studio.",
    benefits: ["100+ pre-built dashboards", "No-code analytics studio", "Predictive attrition modelling", "DEI dashboards", "Cost per hire & per FTE", "Export to BI tools"],
    features: [
      { title: "Pre-Built Dashboards", desc: "100+ ready dashboards across headcount, hiring, performance, learning and cost." },
      { title: "Analytics Studio", desc: "Drag-and-drop studio to build any chart, table or pivot in minutes." },
      { title: "Predictive Models", desc: "Predict attrition, hiring success and engagement with explainable AI." },
      { title: "DEI Analytics", desc: "Diversity, representation, pay-equity and inclusion dashboards." },
      { title: "Benchmarking", desc: "Compare against industry benchmarks for hiring, attrition and cost." },
      { title: "BI Connectors", desc: "Stream data to Tableau, Power BI, Looker and your data warehouse." },
    ],
    workflow: [
      { title: "Ingest", desc: "Data flows live from every Radix module — no ETL." },
      { title: "Analyse", desc: "Use pre-built dashboards or build your own in the studio." },
      { title: "Predict", desc: "ML models surface risks and opportunities with explainability." },
      { title: "Act", desc: "Insights trigger workflows — succession, learning, retention." },
    ],
    useCases: [
      { title: "CHRO Cockpit", desc: "Real-time view of every people KPI for the board." },
      { title: "Attrition Hotspots", desc: "Identify teams at risk and trigger retention interventions." },
      { title: "DEI Reporting", desc: "Quarterly DEI reports with goals, gaps and progress." },
    ],
    integrations: ["Tableau", "Power BI", "Looker", "Snowflake", "BigQuery", "Databricks"],
    dashboard: { title: "CHRO Cockpit", metrics: [
      { label: "Headcount", value: "12,840" },
      { label: "Attrition (TTM)", value: "8.4%" },
      { label: "Cost per FTE", value: "₹16.7 L" },
      { label: "Engagement Index", value: "82" },
    ]},
    intro: "Radix Workforce Analytics turns every people decision into a data-driven one. 100+ pre-built dashboards and a no-code studio give every leader — from CHRO to line manager — real-time visibility into the metrics that matter.",
    body: "Data flows live from every Radix module without ETL. Pre-built dashboards cover headcount, hiring, performance, learning, cost and DEI. The drag-and-drop studio lets analysts build any chart, table or pivot in minutes. Predictive models — attrition risk, hiring success, engagement — come with explainability and recommended actions. BI connectors stream data to Tableau, Power BI, Looker and your data warehouse for advanced analytics.",
    faqs: [
      { q: "Can I build custom dashboards?", a: "Yes. The no-code studio supports any chart, table, pivot, KPI and filter — saved per role." },
      { q: "How accurate are the predictive models?", a: "Attrition models achieve 80%+ precision on rolling validation across customer datasets with explainability." },
      { q: "Can I export data to my warehouse?", a: "Yes. Streaming and batch connectors for Snowflake, BigQuery, Databricks, Redshift and S3/Azure Blob." },
      { q: "Is row-level security supported?", a: "Yes. RLS enforces who can see which data based on org structure, role and custom rules." },
    ],
    related: ["people-analytics", "performance-management", "workforce-planning", "core-hr"],
  }),

  base({
    slug: "people-analytics", category: "Analytics", name: "People Analytics",
    hero: { title: "Predictive People Analytics, Powered by AI",
      subtitle: "Predict attrition, model engagement, simulate org changes and quantify the people impact of every decision." },
    metaTitle: "People Analytics Software — Radix StratEdge",
    metaDescription: "Predictive people analytics with attrition modelling, engagement insights and org simulation.",
    benefits: ["Attrition prediction with drivers", "Engagement & sentiment analysis", "Pay-equity analytics", "Org simulation", "Cost-of-attrition modelling", "Explainable AI"],
    features: [
      { title: "Attrition AI", desc: "Predict 90-day attrition risk per employee with explainable drivers." },
      { title: "Engagement Models", desc: "Combine survey, behaviour and performance data into a real-time engagement index." },
      { title: "Pay-Equity Analytics", desc: "Detect unexplained pay gaps across gender, ethnicity, geography and role." },
      { title: "Org Simulation", desc: "Simulate restructures, role changes and cost impact in minutes." },
      { title: "Cost of Attrition", desc: "Quantify the cost of turnover by role, team and geography." },
      { title: "Explainable AI", desc: "Every prediction comes with feature importance and recommended actions." },
    ],
    workflow: [
      { title: "Train", desc: "Models train on your data with privacy and governance controls." },
      { title: "Predict", desc: "Daily predictions with confidence scores and drivers." },
      { title: "Explain", desc: "Every prediction includes drivers and recommended interventions." },
      { title: "Act", desc: "Predictions trigger workflows — manager nudges, retention plans, surveys." },
    ],
    useCases: [
      { title: "Retention", desc: "Predict and prevent attrition with targeted interventions." },
      { title: "DEI & Pay Equity", desc: "Quantify gaps and track closure across cycles." },
      { title: "Restructure Planning", desc: "Simulate org changes with cost and capability impact." },
    ],
    integrations: ["Snowflake", "BigQuery", "Databricks", "Tableau", "Power BI"],
    dashboard: { title: "Attrition Risk — Live", metrics: [
      { label: "High-Risk Employees", value: "418" },
      { label: "Predicted 90d Loss", value: "184" },
      { label: "Avg Confidence", value: "84%" },
      { label: "Estimated Cost", value: "₹38 Cr" },
    ]},
    intro: "Radix People Analytics moves HR from rear-view reporting to forward-looking decision-making. Predictive models, explainable AI and org simulation give CHROs the same analytical horsepower their CFOs have enjoyed for decades.",
    body: "Attrition models predict 90-day risk per employee with explainable drivers and recommended actions. Engagement models combine survey, behaviour and performance data into a real-time engagement index. Pay-equity analytics detect unexplained gaps across gender, ethnicity, geography and role. Org simulation lets leaders model restructures, role changes and cost impact in minutes. Every prediction is explainable, every model is governed and every recommendation comes with a measurable expected impact.",
    faqs: [
      { q: "How are predictive models trained?", a: "Models train on your historical data with strict privacy and governance — no cross-tenant data sharing." },
      { q: "Are predictions explainable?", a: "Yes. Every prediction includes top drivers, confidence and recommended actions — never a black box." },
      { q: "Can I run pay-equity analysis?", a: "Yes. Detect unexplained pay gaps across gender, ethnicity, geography and role with regression-based controls." },
      { q: "Is it GDPR/DPDPA compliant?", a: "Yes. Models respect data residency, consent and minimisation requirements, with role-based access to predictions." },
    ],
    related: ["workforce-analytics", "performance-management", "career-development", "core-hr"],
  }),

  base({
    slug: "security-compliance", category: "Enterprise", name: "Security & Compliance",
    hero: { title: "Enterprise-Grade Security & Compliance, By Default",
      subtitle: "ISO 27001, SOC 2 Type II, GDPR, DPDPA — built into every layer of the platform." },
    metaTitle: "Security & Compliance — Radix StratEdge",
    metaDescription: "ISO 27001, SOC 2 Type II, GDPR and DPDPA aligned platform with encryption, audit and data residency.",
    benefits: ["ISO 27001 & SOC 2 Type II", "GDPR & DPDPA aligned", "Encryption at rest & in transit", "Data residency in India, EU, US, APAC", "RBAC & field-level masking", "Immutable audit trail"],
    features: [
      { title: "Certifications", desc: "ISO 27001, SOC 2 Type II, ISO 27701 with annual third-party audits." },
      { title: "Encryption", desc: "AES-256 at rest, TLS 1.3 in transit, customer-managed keys (CMK) available." },
      { title: "Data Residency", desc: "Choose data residency in India, EU, US or APAC with isolated infrastructure." },
      { title: "RBAC", desc: "Granular role-based access with field-level masking and segregation of duties." },
      { title: "Audit Trail", desc: "Immutable, exportable audit trail covering every CRUD operation and login." },
      { title: "SSO & MFA", desc: "SAML, OIDC, MFA, device trust and conditional access policies." },
    ],
    workflow: [
      { title: "Architect", desc: "Defense-in-depth with isolated tenants, encrypted storage and zero-trust networking." },
      { title: "Operate", desc: "24x7 SOC, vulnerability management and patch management." },
      { title: "Audit", desc: "Annual ISO and SOC audits with customer evidence packs." },
      { title: "Respond", desc: "Documented IR playbooks, customer notifications and RCAs." },
    ],
    useCases: [
      { title: "Regulated Industries", desc: "Banking, healthcare and pharma rely on Radix for HR compliance." },
      { title: "Global Enterprises", desc: "Data residency by region with cross-border data transfer controls." },
      { title: "Public Sector", desc: "Government-grade controls with on-premise and air-gapped options." },
    ],
    integrations: ["Okta", "Azure AD", "Google", "Splunk", "Datadog", "Sumo Logic"],
    dashboard: { title: "Security Posture", metrics: [
      { label: "Uptime (90d)", value: "99.99%" },
      { label: "Vulns Open", value: "0 Critical" },
      { label: "Audit Findings", value: "0 Open" },
      { label: "MFA Coverage", value: "100%" },
    ]},
    intro: "Radix StratEdge is built for organisations that cannot compromise on security. Every layer — infrastructure, application, data, identity and operations — is engineered to meet the world's most demanding compliance frameworks.",
    body: "Radix holds ISO 27001, SOC 2 Type II and ISO 27701 certifications with annual third-party audits. Data is encrypted with AES-256 at rest and TLS 1.3 in transit, with customer-managed key options for the most sensitive deployments. Data residency choices in India, EU, US and APAC let global enterprises meet cross-border data transfer rules. Role-based access with field-level masking and segregation of duties governs every interaction. An immutable, exportable audit trail covers every CRUD operation and login. A 24x7 SOC, vulnerability management and documented incident response complete a defense-in-depth posture.",
    faqs: [
      { q: "Which certifications do you hold?", a: "ISO 27001, SOC 2 Type II, ISO 27701 — with annual third-party audits and customer evidence packs available." },
      { q: "Where is data stored?", a: "Customer-selected data residency in India, EU, US or APAC — with isolated infrastructure and no cross-region replication." },
      { q: "Do you support customer-managed keys?", a: "Yes. Enterprise customers can bring their own key (BYOK) via AWS KMS, Azure Key Vault or GCP KMS." },
      { q: "How is identity managed?", a: "SAML 2.0, OIDC, MFA, device trust and conditional access policies — with provisioning via SCIM 2.0." },
    ],
    related: ["integrations", "api-platform", "core-hr", "people-analytics"],
  }),

  base({
    slug: "integrations", category: "Enterprise", name: "Integrations",
    hero: { title: "300+ Pre-Built Integrations Across Your Stack",
      subtitle: "ERP, finance, identity, collaboration, learning, BI — Radix plugs into the systems you already run." },
    metaTitle: "HRMS Integrations — Radix StratEdge",
    metaDescription: "300+ pre-built integrations across ERP, finance, identity, collaboration, learning, BI and more.",
    benefits: ["300+ pre-built connectors", "Real-time and batch sync", "iPaaS-friendly architecture", "Webhook events on every change", "Pre-built Workato & Tray recipes", "Marketplace of partner apps"],
    features: [
      { title: "Pre-Built Connectors", desc: "300+ ready integrations across ERP, finance, identity, collaboration, learning and BI." },
      { title: "Event Webhooks", desc: "Subscribe to events — hire, leave, separation — with retries and replay." },
      { title: "iPaaS Recipes", desc: "Ready recipes for Workato, Tray.io, MuleSoft and Zapier." },
      { title: "Custom Connectors", desc: "Build custom connectors with our SDK and connector studio." },
      { title: "Bulk Sync", desc: "Initial and reconciliation syncs with parallel workers and checkpoints." },
      { title: "Marketplace", desc: "Browse and install pre-built partner apps from the Radix Marketplace." },
    ],
    workflow: [
      { title: "Discover", desc: "Browse the marketplace for ready integrations." },
      { title: "Connect", desc: "Authenticate via OAuth or API key in minutes." },
      { title: "Map", desc: "Map fields and configure sync direction with templates." },
      { title: "Monitor", desc: "Dashboards show sync health, errors and replay actions." },
    ],
    useCases: [
      { title: "Identity Provisioning", desc: "Sync hires to Okta, Azure AD with SCIM 2.0 in real time." },
      { title: "Finance Posting", desc: "Post payroll journals to SAP, Oracle, NetSuite or Tally." },
      { title: "Collaboration Sync", desc: "Sync org and groups to Slack, Teams and Google Workspace." },
    ],
    integrations: ["SAP", "Oracle", "Workday", "NetSuite", "Okta", "Azure AD", "Slack", "Teams", "DocuSign", "LinkedIn", "Tally", "Zoho", "HubSpot", "Jira", "ServiceNow"],
    dashboard: { title: "Integration Health", metrics: [
      { label: "Active Connectors", value: "184" },
      { label: "Events / Day", value: "2.4M" },
      { label: "Sync Success", value: "99.97%" },
      { label: "Avg Latency", value: "180 ms" },
    ]},
    intro: "Radix is engineered to be the connective tissue across your enterprise stack. 300+ pre-built integrations, an event-driven architecture and a robust API platform mean Radix data is always where you need it — without custom code.",
    body: "Pre-built connectors cover every category — ERP (SAP, Oracle, NetSuite, Tally), identity (Okta, Azure AD, Google), collaboration (Slack, Teams), learning (Coursera, LinkedIn Learning), BI (Tableau, Power BI) and more. Event-driven webhooks let you subscribe to any change — hire, leave, separation, payroll run — with retries and replay. iPaaS recipes for Workato, Tray.io, MuleSoft and Zapier accelerate complex flows. A connector SDK and marketplace let partners and customers extend the ecosystem.",
    faqs: [
      { q: "How many integrations are pre-built?", a: "300+ across ERP, finance, identity, collaboration, learning, BI and more — with new connectors monthly." },
      { q: "Do you support webhooks?", a: "Yes. Subscribe to any event with HMAC-signed payloads, retries, dead-letter queue and replay." },
      { q: "Can I build custom integrations?", a: "Yes. REST API, GraphQL, webhooks and a connector SDK let you build any custom integration." },
      { q: "Is SCIM supported?", a: "Yes. SCIM 2.0 for user, group and role provisioning with Okta, Azure AD, OneLogin and JumpCloud." },
    ],
    related: ["api-platform", "security-compliance", "core-hr", "payroll-management"],
  }),

  base({
    slug: "api-platform", category: "Enterprise", name: "API Platform",
    hero: { title: "A Modern API Platform for Developers",
      subtitle: "REST, GraphQL, webhooks and SDKs — with first-class docs, sandboxes and rate-limit transparency." },
    metaTitle: "HRMS API Platform — Radix StratEdge",
    metaDescription: "REST, GraphQL, webhooks and SDKs for building integrations and apps on top of Radix StratEdge.",
    benefits: ["REST + GraphQL APIs", "Webhook events", "SDKs (Node, Python, Java, .NET)", "OpenAPI 3.1 docs", "Sandbox environments", "Transparent rate limits"],
    features: [
      { title: "REST API", desc: "Full-coverage REST API with OpenAPI 3.1 and Postman collection." },
      { title: "GraphQL", desc: "Type-safe GraphQL with subscriptions for real-time clients." },
      { title: "Webhooks", desc: "HMAC-signed events with retries, dead-letter queue and replay UI." },
      { title: "SDKs", desc: "Official SDKs in Node, Python, Java, .NET, Go and PHP." },
      { title: "Sandbox", desc: "Free developer sandbox with seed data and reset capability." },
      { title: "Rate Limits", desc: "Per-app rate limits with headers, dashboards and burst credits." },
    ],
    workflow: [
      { title: "Sign Up", desc: "Create a developer account and sandbox in minutes." },
      { title: "Build", desc: "Use SDKs or REST/GraphQL with first-class docs." },
      { title: "Test", desc: "Run integration tests against the sandbox with seed data." },
      { title: "Launch", desc: "Promote to production with versioning and changelog." },
    ],
    useCases: [
      { title: "Internal Apps", desc: "Build internal apps on top of Radix data." },
      { title: "Partner Apps", desc: "Build and publish partner apps to the Radix Marketplace." },
      { title: "Custom Integrations", desc: "Connect any system not covered by pre-built connectors." },
    ],
    integrations: ["Postman", "Insomnia", "Apollo", "Hasura"],
    dashboard: { title: "API Health", metrics: [
      { label: "Apps", value: "1,420" },
      { label: "API Calls / Day", value: "184M" },
      { label: "Avg Latency", value: "120 ms" },
      { label: "Error Rate", value: "0.02%" },
    ]},
    intro: "Radix is built API-first. Every screen in the product calls the same public API that's available to developers, partners and customers — giving you a complete, well-documented platform to build on.",
    body: "Full-coverage REST and GraphQL APIs, HMAC-signed webhooks and official SDKs in 6 languages make integration a first-class experience. OpenAPI 3.1 docs, Postman collections and interactive sandboxes accelerate development. Per-app rate limits with headers and burst credits give developers transparent, predictable behaviour. Versioning, deprecation policies and changelogs respect your build cycles.",
    faqs: [
      { q: "Is the API the same as what the UI uses?", a: "Yes. Radix is API-first — every UI feature calls the same public API." },
      { q: "Are there official SDKs?", a: "Yes. Node, Python, Java, .NET, Go and PHP — all open source on GitHub." },
      { q: "Is there a sandbox?", a: "Yes. Free developer sandbox with seed data, reset capability and full API access." },
      { q: "How are rate limits handled?", a: "Per-app rate limits with response headers, dashboards and burst credits — published in the docs." },
    ],
    related: ["integrations", "security-compliance", "core-hr", "workforce-analytics"],
  }),
];

export const productMap: Record<string, ProductContent> = Object.fromEntries(products.map((p) => [p.slug, p]));
