export type SeoContent = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  body1: string;
  body2: string;
  bullets: string[];
  highlights: { title: string; desc: string }[];
  faqs: { q: string; a: string }[];
  related: { label: string; to: string }[];
};

const s = (x: SeoContent): SeoContent => x;

const stdFaqs = (topic: string) => [
  { q: `Is ${topic} cloud-based?`, a: `Yes. Radix StratEdge is a cloud-native, multi-tenant SaaS platform with 99.99% uptime SLAs, hosted on enterprise-grade infrastructure with data residency choices in India, EU, US and APAC.` },
  { q: `How long does implementation take?`, a: `Most ${topic} implementations go live in 4–8 weeks with our experienced implementation team. Complex multi-entity rollouts can complete in 8–12 weeks.` },
  { q: `What does ${topic} cost?`, a: `Pricing is per-employee-per-month with transparent module-based plans. Volume discounts, multi-year terms and enterprise agreements are available — see our pricing page or talk to sales for a tailored quote.` },
  { q: `Does ${topic} support Indian compliance?`, a: `Yes. Radix StratEdge is built for Indian statutory compliance — PF, ESI, PT, TDS, LWF, Gratuity, Bonus Act, Shops & Establishments, Contract Labour Act and state-specific filings.` },
];

export const seoPages: SeoContent[] = [
  s({
    slug: "hrms-software-india",
    title: "Best HRMS Software in India",
    metaTitle: "Best HRMS Software in India — Radix StratEdge People Cloud",
    metaDescription: "India's leading AI-powered HRMS software for end-to-end employee lifecycle, payroll, attendance, performance and learning.",
    intro: "Radix StratEdge People Cloud is the leading enterprise HRMS software in India, delivering a unified Hire-to-Retire platform for over 2,500 organisations across manufacturing, IT services, healthcare, retail and BFSI. Built specifically for the complexity of Indian compliance and the scale of modern Indian enterprises, Radix combines core HR, payroll, attendance, performance, learning and analytics into a single AI-powered cloud platform.",
    body1: "Indian HR teams need a system that understands the country's unique statutory landscape — PF, ESI, PT, TDS, LWF, Gratuity, Bonus Act, Shops & Establishments and Contract Labour Act — while scaling to thousands of employees across multiple entities, states and locations. Radix StratEdge is engineered from the ground up for this reality. Pre-built statutory engines, multi-state compliance, state-wise PT slabs and ECR generation come out of the box. Multi-entity, multi-currency and multi-country architecture lets Indian enterprises with global operations standardise on one platform.",
    body2: "Beyond compliance, Radix delivers the modern employee experience expected by today's workforce. A mobile-first ESS app handles payslips, leave, attendance, helpdesk and learning. An AI HR assistant answers policy questions in natural language across 20+ Indian and global languages. People analytics dashboards give CHROs real-time visibility into headcount, attrition, engagement and cost. Predictive AI flags attrition risks early, recommends interventions and quantifies the cost of inaction — turning HR from a reactive function into a strategic advantage.",
    bullets: ["End-to-end Hire-to-Retire on one platform", "Pre-built Indian statutory compliance", "Multi-entity & multi-state architecture", "AI-powered people analytics", "Mobile-first employee experience", "300+ integrations including SAP, Tally, NetSuite"],
    highlights: [
      { title: "Trusted by 2,500+ Indian Enterprises", desc: "From manufacturing giants to fast-growing unicorns." },
      { title: "Built for Indian Compliance", desc: "PF, ESI, PT, TDS, LWF, Gratuity, Bonus Act — all pre-configured." },
      { title: "Enterprise-Grade Security", desc: "ISO 27001, SOC 2 Type II, DPDPA aligned." },
    ],
    faqs: stdFaqs("HRMS software"),
    related: [
      { label: "Payroll Software India", to: "/payroll-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "Enterprise HRMS Software", to: "/enterprise-hrms-software" },
      { label: "Cloud HRMS Software", to: "/cloud-hrms-software" },
    ],
  }),
  s({
    slug: "payroll-software-india",
    title: "Payroll Software India",
    metaTitle: "Best Payroll Software in India — Radix StratEdge",
    metaDescription: "Automated payroll software for Indian enterprises with PF, ESI, PT, TDS, LWF compliance and bank-ready transfer files.",
    intro: "Radix StratEdge Payroll is the payroll software trusted by leading Indian enterprises to run accurate, compliant and on-time payroll for millions of employees every month. Pre-built statutory engines for PF, ESI, PT, TDS, LWF, Gratuity and Bonus Act make Indian compliance effortless, while a flexible salary structure engine and full integration with attendance, leave and finance systems eliminate the manual work that plagues legacy payroll setups.",
    body1: "Payroll in India is uniquely complex. Multiple states with different PT slabs, frequent statutory changes, region-specific labour laws, contract labour exposure and the perennial challenge of integrating with finance and banking systems can turn payroll processing into a weeks-long ordeal. Radix Payroll simplifies all of this with a metadata-driven engine that handles unlimited salary structures, formula-based components, eligibility rules, effective-dated changes and grandfathering. Multi-state PT, statutory ceilings, ESI eligibility, PF wage caps and TDS calculations all happen automatically.",
    body2: "The platform integrates seamlessly with attendance, leave, reimbursements, loans, advances and Flexible Benefits Plan submissions — every input is captured with a complete audit trail. Multi-level approval workflows enforce segregation of duties. Bank transfer files for 200+ Indian and global banks are generated in seconds, and statutory challans, Form 16, Form 24Q, Form 12BA and ECR files are produced ready for filing. A real-time variance dashboard catches anomalies before disbursement, giving payroll teams the confidence to close cycles in hours instead of days.",
    bullets: ["PF, ESI, PT, TDS, LWF, Gratuity automation", "Multi-state and multi-entity support", "Form 16, 24Q, 12BA & ECR generation", "Bank files for 200+ Indian banks", "Flexible Benefits Plan (FBP)", "Loans, advances and reimbursements"],
    highlights: [
      { title: "99.99% Calculation Accuracy", desc: "Backed by an SLA across millions of payslips monthly." },
      { title: "Payroll in Hours, Not Days", desc: "Customers report payroll cycles closing 80% faster." },
      { title: "Audit-Ready Always", desc: "Complete audit trail for every change, override and approval." },
    ],
    faqs: stdFaqs("payroll software"),
    related: [
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "Leave Management Software", to: "/leave-management-software" },
      { label: "Enterprise HRMS Software", to: "/enterprise-hrms-software" },
    ],
  }),
  s({
    slug: "attendance-management-software",
    title: "Attendance Management Software",
    metaTitle: "Attendance Management Software — Radix StratEdge",
    metaDescription: "Cloud attendance management with geo-fencing, biometric, mobile selfie and shift-aware capture for distributed workforces.",
    intro: "Modern workforces are mobile, hybrid, shift-based and spread across hundreds of sites. Radix StratEdge Attendance Management Software unifies every capture mode — web, mobile, geo-fenced selfie, biometric and RFID — into a single shift-aware engine that feeds payroll, compliance and analytics in real time.",
    body1: "Whether you're managing a 10,000-strong manufacturing workforce across multiple plants, a national retail chain with thousands of store associates, or a hybrid corporate office with desk booking, Radix scales to your operating model. Geo-fenced mobile capture works offline, with tamper-evident hashing and anti-spoof detection to prevent ghost-worker fraud. Biometric integrations cover 50+ device brands across face, fingerprint and RFID, with automatic device-health monitoring. Shift-aware rules handle overtime, comp-off, statutory rest periods and union obligations automatically.",
    body2: "Exception workflows route tardiness, missed punches and overtime requests to the right manager with single-click approvals and full context. Every transaction is logged for audit. Real-time dashboards surface floor utilisation, absenteeism, shift coverage and overtime trends across every site. Direct integration with Radix Payroll, Leave and Analytics means attendance data flows downstream without manual export — eliminating the reconciliation errors and end-of-month panic that legacy attendance systems create.",
    bullets: ["Geo-fenced mobile attendance", "Biometric & RFID device integration", "Shift, OT and comp-off rules", "Offline punch with auto-sync", "Real-time exception alerts", "Direct payroll integration"],
    highlights: [
      { title: "5+ Capture Modes", desc: "Web, mobile, geo-fenced selfie, biometric, RFID — pick what suits each site." },
      { title: "Anti-Spoof Detection", desc: "Detects mock-location, rooted devices, emulators and impossible travel." },
      { title: "Real-Time Visibility", desc: "Live floor utilisation, absenteeism and OT across every site." },
    ],
    faqs: stdFaqs("attendance management software"),
    related: [
      { label: "Leave Management Software", to: "/leave-management-software" },
      { label: "Payroll Software India", to: "/payroll-software-india" },
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "leave-management-software",
    title: "Leave Management Software",
    metaTitle: "Leave Management Software — Radix StratEdge",
    metaDescription: "Configurable leave management with policies, accruals, carry-forward, encashment and approval workflows for enterprises.",
    intro: "Radix StratEdge Leave Management Software handles every leave policy an enterprise can throw at it — annual, sick, casual, parental, sabbatical, comp-off, statutory and bespoke — with automatic accruals, carry-forward, encashment and lapse processing across multiple geographies and entities.",
    body1: "Administrators build leave policies in a no-code studio with rules for eligibility, accrual frequency, caps, prorations and lapse behaviour. Holiday calendars are maintained per location, entity or employee group, with auto-application on payroll runs. Approval workflows can be sequential, parallel or matrix-based with delegation and auto-escalation when SLAs are missed. Employees apply via web, mobile or Slack with real-time balance checks and team-calendar conflict detection.",
    body2: "Year-end processing — carry-forward, encashment, lapse — runs automatically with payroll integration and a complete audit trail. Managers get team-calendar views to plan coverage, and the platform alerts them when too many team members request the same dates. Integrations with Outlook, Google Calendar, Slack and Microsoft Teams keep approved leave visible in personal calendars and team channels — eliminating the surprise absences that disrupt operations.",
    bullets: ["Unlimited leave types and policies", "Holiday calendars per location/entity", "Multi-level approval chains", "Carry-forward and encashment automation", "Outlook & Google Calendar sync", "Mobile and Slack apply flow"],
    highlights: [
      { title: "Any Policy, Any Geography", desc: "Configure unlimited leave types with bespoke rules per entity or location." },
      { title: "Year-End on Autopilot", desc: "Carry-forward, encashment and lapse run automatically with payroll integration." },
      { title: "Calendar-First Workflow", desc: "Approved leave syncs to Outlook, Google Calendar, Slack and Teams." },
    ],
    faqs: stdFaqs("leave management software"),
    related: [
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "Employee Self Service Software", to: "/employee-self-service-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "Payroll Software India", to: "/payroll-software-india" },
    ],
  }),
  s({
    slug: "employee-self-service-software",
    title: "Employee Self Service Software",
    metaTitle: "Employee Self Service Software — Radix StratEdge",
    metaDescription: "Modern ESS portal and mobile app with payslips, leave, attendance, helpdesk and AI HR assistant.",
    intro: "Radix StratEdge Employee Self Service software turns the daily HR experience from frustrating to delightful. A modern, mobile-first interface — backed by a conversational AI assistant — lets employees handle payslips, leave, attendance, helpdesk, announcements and profile updates without ever opening a ticket with HR.",
    body1: "The Radix ESS mobile apps are native, fast and built for low-data environments — ideal for retail, manufacturing, logistics and field workforces. SSO with Okta, Azure AD, Google Workspace and 30+ identity providers means zero password fatigue. A multi-category helpdesk with SLA tracking, escalation paths and a knowledge base reduces L1 HR effort by 60%+. The built-in AI assistant answers policy questions, generates letters, summarises payslips and walks employees through self-service flows in natural language across English, Hindi and 20+ languages.",
    body2: "Beyond core self-service, the platform delivers an engaging employee experience with personalised announcements, polls, recognition, learning recommendations and pulse surveys. Push notifications keep employees informed about payroll dates, leave approvals, learning deadlines and company news. The result is an ESS that employees actually open every day — turning the HR app from a once-a-month necessity into a daily companion that drives engagement, productivity and retention.",
    bullets: ["Native iOS and Android apps", "AI HR assistant in 20+ languages", "Helpdesk with SLA and CSAT", "Payslip, tax docs and FBP", "Single sign-on with Okta/Azure AD", "Announcements, polls and recognition"],
    highlights: [
      { title: "Loved by Frontline Workers", desc: "Optimised for low-data, low-spec devices used by store and plant teams." },
      { title: "AI That Actually Helps", desc: "Conversational HR assistant trained on your policies and handbook." },
      { title: "60%+ HR Ticket Reduction", desc: "Self-service plus AI cuts repetitive L1 HR queries by more than half." },
    ],
    faqs: stdFaqs("employee self service software"),
    related: [
      { label: "Leave Management Software", to: "/leave-management-software" },
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
  s({
    slug: "applicant-tracking-system",
    title: "Applicant Tracking System (ATS)",
    metaTitle: "Best Applicant Tracking System (ATS) — Radix StratEdge",
    metaDescription: "AI-powered ATS with multi-channel sourcing, resume screening, interview scheduling and offer management.",
    intro: "Radix StratEdge Applicant Tracking System is built for recruiting teams that hire at scale without sacrificing candidate experience. A unified workspace combines sourcing, screening, scheduling, assessments and offer management — with AI woven through every step to amplify recruiter productivity by 3x or more.",
    body1: "Multi-channel sourcing reaches 30+ job boards, premium professional networks, employee referrals and agency portals in one click. AI resume parsing extracts structured data with 95%+ accuracy across English, Hindi and 15+ languages, while explainable screening models rank candidates against requisition requirements and surface diversity considerations. Self-scheduling eliminates email tag — candidates pick from real-time interviewer availability across panels and time zones, with calendar conflicts and travel time auto-handled.",
    body2: "Branded careers sites are built with drag-and-drop blocks and optimised for SEO, with custom domains, accessibility compliance and integrated analytics. Offer management includes salary calculators, approval matrices, e-signatures via DocuSign or Adobe Sign, and seamless handoff to onboarding. Real-time recruiter analytics track pipeline velocity, source effectiveness, recruiter load, time-to-hire, time-to-fill, offer-accept rate and diversity metrics. The platform is purpose-built to scale from a 50-hire boutique to a 50,000-hire enterprise without changing tools.",
    bullets: ["30+ job board integrations", "AI resume parsing & screening", "Self-scheduling for panels", "Branded SEO careers site", "Offer letters with e-signature", "Recruiter productivity dashboards"],
    highlights: [
      { title: "3x Recruiter Productivity", desc: "AI shortlisting and self-scheduling free recruiters for high-value work." },
      { title: "Bias-Aware AI", desc: "Explainable screening with diversity considerations baked in." },
      { title: "Scales to 50,000+ Hires", desc: "From boutique to enterprise on a single platform." },
    ],
    faqs: stdFaqs("applicant tracking system"),
    related: [
      { label: "Recruitment Software", to: "/recruitment-management-software" },
      { label: "Onboarding Software", to: "/employee-onboarding-software" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "recruitment-management-software",
    title: "Recruitment Management Software",
    metaTitle: "Recruitment Management Software — Radix StratEdge",
    metaDescription: "End-to-end recruitment management software from requisition to offer with AI screening and vendor portals.",
    intro: "Radix StratEdge Recruitment Management Software covers the complete recruiting lifecycle — from manpower requisition to offer acceptance and onboarding handoff — with AI-driven productivity tools, vendor management and analytics that transform how enterprises hire.",
    body1: "The platform starts with structured manpower planning and requisitions tied to approved budgets and headcount plans. Requisitions flow through configurable approval matrices before opening to sourcing — internal mobility, employee referrals, job boards, social media, recruitment vendors and campus drives all run through one workspace. Vendor portals let agencies submit candidates directly with status visibility, billing and compliance built in. Internal mobility marketplaces let employees apply to open roles with skill-matching and manager-of-record consent.",
    body2: "AI does the heavy lifting in screening and shortlisting, with explainable scoring against requisition requirements. Interview workflows handle scheduling, scorecards and panel feedback. Offer management automates letter generation, salary calculations, approval cycles and e-signature collection. End-to-end analytics — from requisition aging to offer-accept rates by source — let TA leaders optimise every step. The result is a recruitment engine that reduces time-to-hire by 30%+ while improving quality of hire and candidate experience.",
    bullets: ["Manpower planning & requisitions", "Multi-channel sourcing", "Vendor portal with billing", "Internal mobility marketplace", "Interview workflows & scorecards", "Offer management & e-signature"],
    highlights: [
      { title: "End-to-End Lifecycle", desc: "Requisition to offer to onboarding in one connected platform." },
      { title: "Vendor Management Built In", desc: "Agency submissions, billing and compliance — no spreadsheets." },
      { title: "30% Faster Time-to-Hire", desc: "AI screening and self-scheduling compress the cycle dramatically." },
    ],
    faqs: stdFaqs("recruitment management software"),
    related: [
      { label: "Applicant Tracking System", to: "/applicant-tracking-system" },
      { label: "Onboarding Software", to: "/employee-onboarding-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
  s({
    slug: "employee-onboarding-software",
    title: "Employee Onboarding Software",
    metaTitle: "Employee Onboarding Software — Radix StratEdge",
    metaDescription: "Automated employee onboarding with pre-boarding portals, document collection, e-signatures and 30-60-90 day journeys.",
    intro: "First impressions matter. Radix StratEdge Employee Onboarding Software turns offer-letter acceptance into a structured, engaging journey that has new hires productive in weeks — not months — while eliminating the manual coordination that drains HR and IT teams.",
    body1: "From the moment a candidate accepts, a branded pre-boarding portal welcomes them with personalised content, document checklists, buddy introductions, team videos and a glimpse of their day-one workspace. Document collection is OCR-driven with automatic statutory validation. Background verification workflows trigger third-party checks and surface red flags before day one. IT and asset provisioning happens automatically via integrations with Jira, ServiceNow, Okta, Azure AD and your MDM — laptops, badges, software access, email and Slack are ready when the new hire walks in.",
    body2: "Structured 30-60-90 day journeys assign tasks, learning paths, mentor sessions and pulse surveys — giving managers a single cockpit to spot risks early and celebrate wins. Customisable templates per role, level, location and business unit let HR build the right onboarding experience for every persona — from campus hires to executive joiners to remote employees in different time zones. The platform reduces time-to-productivity by 30%+ and lifts 90-day retention rates significantly.",
    bullets: ["Branded pre-boarding portal", "OCR document collection", "BGV workflow integration", "IT & asset provisioning", "30-60-90 day journey templates", "Manager cockpit & analytics"],
    highlights: [
      { title: "Engaged From Day Minus 7", desc: "Pre-boarding portal builds excitement before the new hire shows up." },
      { title: "IT Ready on Day One", desc: "Automated provisioning ensures every joiner is fully equipped." },
      { title: "30%+ Faster Productivity", desc: "Structured journeys accelerate ramp and reduce 90-day attrition." },
    ],
    faqs: stdFaqs("employee onboarding software"),
    related: [
      { label: "Applicant Tracking System", to: "/applicant-tracking-system" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "Performance Management Software", to: "/performance-management-software" },
      { label: "Learning Management System", to: "/learning-management-system" },
    ],
  }),
  s({
    slug: "performance-management-software",
    title: "Performance Management Software",
    metaTitle: "Performance Management Software — Radix StratEdge",
    metaDescription: "OKRs, continuous feedback, 360° reviews, calibration and growth planning in one modern performance platform.",
    intro: "Radix StratEdge Performance Management Software replaces the annual-review charade with a continuous performance system that aligns strategy to execution, builds a feedback culture and gives every employee a clear line of sight to their growth and impact.",
    body1: "OKRs cascade from company to team to individual with dependency tracking and weekly check-ins. Goal templates accelerate rollout; alignment views show how every employee's work ladders up to strategic priorities. Continuous feedback — praise, requested, anonymous — flows across the team and surfaces in reviews. Manager 1:1s use structured agendas, action items and recurring cadences that turn the lowest-effort conversation into the highest-impact ritual.",
    body2: "360° reviews collect self, manager, peer, direct-report and stakeholder inputs with configurable weighting and anonymity controls. AI summarises feedback, highlights themes and flags potential bias. Calibration sessions standardise ratings across managers with distribution analytics and bias detection. Promotion and PIP workflows automate packets, approvals and downstream actions like compensation changes and learning enrolments. Tight integration with Learning and Career Development means growth conversations turn into growth actions automatically.",
    bullets: ["OKRs with cascading alignment", "Continuous feedback culture", "360° reviews with weighting", "Manager 1:1 cadence", "Calibration with bias detection", "Promotion & PIP workflows"],
    highlights: [
      { title: "Beyond the Annual Review", desc: "Continuous performance that drives outcomes, not paperwork." },
      { title: "AI-Powered Insights", desc: "Feedback summarisation, theme extraction and bias detection." },
      { title: "Growth That Compounds", desc: "Performance ties directly to learning and career development." },
    ],
    faqs: stdFaqs("performance management software"),
    related: [
      { label: "Learning Management System", to: "/learning-management-system" },
      { label: "HR Analytics Software", to: "/hr-analytics-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
  s({
    slug: "learning-management-system",
    title: "Learning Management System (LMS)",
    metaTitle: "Best Learning Management System (LMS) — Radix StratEdge",
    metaDescription: "Modern enterprise LMS with course builder, learning paths, certifications, gamification and AI recommendations.",
    intro: "Radix StratEdge Learning Management System is the modern enterprise LMS built into your HRMS — eliminating the integration nightmare and learner experience compromise that come with bolt-on learning platforms. From day-one onboarding learning to compliance certifications to leadership development, Radix LMS covers every learning need with one beautiful, mobile-first experience.",
    body1: "A drag-and-drop course builder lets L&D teams assemble courses from videos, articles, quizzes, SCORM and xAPI packages, and even live virtual sessions. Learning paths string courses into structured journeys tied to roles, skills and certifications. Assessments support quizzes, assignments, video submissions, peer review and proctored exams. Gamification — badges, leaderboards, points and challenges — keeps learners engaged. Mobile learning works offline with progress sync, ideal for frontline workers in retail, manufacturing and logistics.",
    body2: "AI recommends learning based on role, skills, goals, performance feedback and peer behaviour. Skill matrices link learning to capability development, with progress visible to learners, managers and HR. Compliance learning includes mandatory training, expiry tracking, certification management and audit-ready reports. Instructor and learner dashboards give L&D leaders real-time visibility into enrolments, completions, scores, time-to-competency and ROI. Integration with Coursera, Udemy Business, LinkedIn Learning and edX brings external content into the same unified experience.",
    bullets: ["Drag-and-drop course builder", "SCORM, xAPI, video and live sessions", "Learning paths and certifications", "Gamification and leaderboards", "Mobile learning with offline support", "AI-powered learning recommendations"],
    highlights: [
      { title: "Built Into Your HRMS", desc: "No bolt-on integration drama — LMS is native to the platform." },
      { title: "Engaging by Design", desc: "Gamification, social learning and mobile-first UX drive completions." },
      { title: "Learning That Maps to Skills", desc: "Skill matrices link every course to measurable capability development." },
    ],
    faqs: stdFaqs("learning management system"),
    related: [
      { label: "LMS Software India", to: "/lms-software-india" },
      { label: "Performance Management Software", to: "/performance-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
  s({
    slug: "lms-software-india",
    title: "Best LMS Software in India",
    metaTitle: "Best LMS Software in India — Radix StratEdge",
    metaDescription: "Leading Learning Management System (LMS) software in India with mobile learning, certifications and AI recommendations.",
    intro: "Radix StratEdge LMS is the leading Learning Management System for Indian enterprises — combining the rigour of compliance learning with the engagement of modern consumer experiences. Built into the Radix People Cloud platform, it eliminates the integration burden of standalone LMS tools while delivering an experience that learners, L&D teams and business leaders all love.",
    body1: "Indian enterprises learning needs are diverse — POSH and compliance training for the corporate workforce, technical upskilling for engineers, sales enablement for distributed teams, leadership development for emerging managers, and foundational skills for frontline workers in retail, manufacturing and logistics. Radix LMS handles all of these on one platform with multi-language support, mobile-first design and offline learning for low-connectivity environments. Vernacular content support spans Hindi, Tamil, Telugu, Bengali, Marathi, Kannada and more.",
    body2: "Compliance learning includes mandatory training assignment, expiry tracking, certification management and audit-ready reports — ready for POSH, anti-bribery, information security and industry-specific requirements. AI recommends learning based on role, skill gaps and career goals. Integration with global content libraries — Coursera, Udemy Business, LinkedIn Learning, edX — brings world-class content into a unified Indian-context experience. Real-time dashboards show enrolments, completions, scores, time-to-competency and ROI by business unit, location and learner cohort.",
    bullets: ["Multi-language and vernacular support", "Mobile-first with offline learning", "POSH & compliance certifications", "AI learning recommendations", "Global content library integration", "L&D ROI dashboards"],
    highlights: [
      { title: "Made for India, Built for the World", desc: "Vernacular learning, Indian compliance, global content library." },
      { title: "Frontline-Ready", desc: "Mobile-first with offline support for retail, manufacturing, logistics." },
      { title: "Native HRMS Integration", desc: "Learning, skills and performance flow naturally — no integration drama." },
    ],
    faqs: stdFaqs("LMS software"),
    related: [
      { label: "Learning Management System", to: "/learning-management-system" },
      { label: "Performance Management Software", to: "/performance-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
  s({
    slug: "workforce-management-software",
    title: "Workforce Management Software",
    metaTitle: "Workforce Management Software — Radix StratEdge",
    metaDescription: "Workforce management software for shifts, rosters, geo attendance, field tracking and workforce planning.",
    intro: "Radix StratEdge Workforce Management Software unifies shift rosters, attendance, leave, timesheets, field tracking and workforce planning into a single platform — purpose-built for enterprises with complex, distributed, shift-based workforces.",
    body1: "Whether you operate manufacturing plants with three-shift rosters, retail stores with peak-aware coverage, hospitals with 24x7 nursing schedules, or logistics networks with thousands of mobile drivers, Radix scales to the complexity. A constraint-based auto-scheduler builds compliant rosters in minutes — respecting statutory rest periods, max hours, skills, certifications, location preferences and union rules. Demand forecasting uses historical and seasonal patterns to right-size coverage by site and time-slot.",
    body2: "Geo-fenced mobile attendance with selfie verification eliminates ghost workers and gives real-time site headcount. Field workforce tools cover beat plans, route adherence, visit logs and live tracking for sales, service and delivery teams. Workforce planning models headcount, cost and capability scenarios for the next 1–5 years. Real-time dashboards surface coverage gaps, attendance exceptions, overtime trends and productivity metrics across every site — turning workforce data into operational insight that drives action.",
    bullets: ["Auto-scheduling with constraints", "Geo-fenced mobile attendance", "Shift swaps & open shifts", "Field workforce tracking", "Workforce planning & scenarios", "Real-time coverage dashboards"],
    highlights: [
      { title: "Built for Operational Complexity", desc: "Multi-plant, multi-store, multi-hub, multi-site — at enterprise scale." },
      { title: "Compliance Without Compromise", desc: "Statutory rest, union rules, max hours — codified in the engine." },
      { title: "Operations-Grade Visibility", desc: "Real-time dashboards across every site, shift and team." },
    ],
    faqs: stdFaqs("workforce management software"),
    related: [
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "Manufacturing HRMS", to: "/manufacturing-hrms" },
      { label: "Retail HRMS", to: "/retail-hrms" },
      { label: "Logistics HRMS", to: "/logistics-hrms" },
    ],
  }),
  s({
    slug: "people-analytics-software",
    title: "People Analytics Software",
    metaTitle: "People Analytics Software — Radix StratEdge",
    metaDescription: "Predictive people analytics with attrition modelling, engagement insights, pay-equity analytics and org simulation.",
    intro: "Radix StratEdge People Analytics Software moves HR from rear-view reporting to forward-looking decision-making. Predictive models, explainable AI and org simulation give CHROs the same analytical horsepower their CFOs have enjoyed for decades — turning people data into strategic advantage.",
    body1: "Attrition models predict 90-day risk per employee with explainable drivers and recommended actions. Engagement models combine survey, behaviour and performance data into a real-time engagement index. Pay-equity analytics detect unexplained gaps across gender, ethnicity, geography and role with regression-based controls. Org simulation lets leaders model restructures, role changes and cost impact in minutes — answering 'what if' questions that previously took weeks of spreadsheet analysis.",
    body2: "Every prediction is explainable — no black-box models that HR can't defend in a boardroom or to a regulator. Every model is governed with privacy, consent and data residency controls. Every recommendation comes with a measurable expected impact, so business leaders can prioritise the interventions that matter most. BI connectors stream data to Tableau, Power BI, Looker, Snowflake, BigQuery and Databricks for further analysis in your existing data stack.",
    bullets: ["Attrition prediction with drivers", "Real-time engagement index", "Pay-equity analytics", "Org simulation in minutes", "Cost-of-attrition modelling", "BI tool connectors"],
    highlights: [
      { title: "Predict, Don't React", desc: "Attrition, engagement and risk surfaced before they become problems." },
      { title: "Explainable AI", desc: "Every prediction defensible in the boardroom and to regulators." },
      { title: "Quantified Impact", desc: "Every intervention with a measurable expected outcome." },
    ],
    faqs: stdFaqs("people analytics software"),
    related: [
      { label: "HR Analytics Software", to: "/hr-analytics-software" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "Enterprise HRMS Software", to: "/enterprise-hrms-software" },
    ],
  }),
  s({
    slug: "hr-analytics-software",
    title: "HR Analytics Software",
    metaTitle: "HR Analytics Software — Radix StratEdge",
    metaDescription: "Real-time HR analytics with pre-built dashboards, predictive models and a no-code analytics studio.",
    intro: "Radix StratEdge HR Analytics Software turns every people decision into a data-driven one. Over 100 pre-built dashboards and a no-code analytics studio give every leader — from CHRO to line manager — real-time visibility into the people metrics that drive business outcomes.",
    body1: "Data flows live from every Radix module without ETL — headcount, hiring, attrition, performance, learning, payroll cost, engagement and DEI all available in real time. Pre-built dashboards cover the full CHRO cockpit, recruiter productivity, learning ROI, payroll cost trends, attrition heatmaps, DEI metrics and operational metrics like attendance and overtime. The no-code studio lets analysts build any chart, table, pivot or KPI in minutes — saved per role with row-level security.",
    body2: "Predictive models — attrition risk, hiring success, engagement scoring — come with explainability and recommended actions. BI connectors stream data to Tableau, Power BI, Looker, Snowflake, BigQuery and Databricks for deeper analysis in your existing data stack. Scheduled exports, alerting on KPI thresholds and embedded dashboards in Slack or Teams put analytics where work happens — driving faster, smarter people decisions across the enterprise.",
    bullets: ["100+ pre-built dashboards", "No-code analytics studio", "Predictive attrition & engagement", "DEI and pay-equity analytics", "BI tool connectors", "Slack/Teams embedded dashboards"],
    highlights: [
      { title: "Real-Time, No ETL", desc: "Data flows live from every module — always fresh, always accurate." },
      { title: "Self-Service for Every Leader", desc: "From CHRO cockpit to line-manager dashboards with role-based access." },
      { title: "Insight Where Work Happens", desc: "Embedded dashboards in Slack, Teams and email — not just a portal." },
    ],
    faqs: stdFaqs("HR analytics software"),
    related: [
      { label: "People Analytics Software", to: "/people-analytics-software" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "Enterprise HRMS Software", to: "/enterprise-hrms-software" },
    ],
  }),
  s({
    slug: "cloud-hrms-software",
    title: "Cloud HRMS Software",
    metaTitle: "Cloud HRMS Software — Radix StratEdge",
    metaDescription: "Cloud-native HRMS software with 99.99% uptime SLA, auto-scaling and zero-touch upgrades.",
    intro: "Radix StratEdge Cloud HRMS Software is a fully cloud-native, multi-tenant SaaS platform built for the scale, agility and security expectations of modern enterprises. Unlike legacy HR systems that were retrofitted to the cloud, Radix is engineered from the ground up on cloud-native principles — delivering 99.99% uptime, elastic auto-scaling, zero-touch upgrades and global data residency choices.",
    body1: "The platform runs on enterprise-grade infrastructure with isolated tenants, encrypted storage and zero-trust networking. Customers choose data residency in India, EU, US or APAC with no cross-region replication. Quarterly product upgrades roll out automatically with zero downtime, ensuring every customer benefits from new features, performance improvements and security patches without IT involvement. SLAs cover availability, response time, support response and security incident notification with financial credits for breaches.",
    body2: "Cloud-native architecture means linear scaling from 100 to 100,000 employees without architecture changes. Elastic compute handles month-end payroll spikes, quarter-end performance reviews and peak-hiring seasons without performance degradation. Modern APIs, webhooks, streaming connectors and SDKs make integration into your stack effortless. A 24x7 SOC, vulnerability management, penetration testing and bug bounty program complete a defense-in-depth security posture aligned to ISO 27001, SOC 2 Type II, GDPR and DPDPA.",
    bullets: ["99.99% uptime SLA", "Auto-scaling for peak workloads", "Zero-touch quarterly upgrades", "Global data residency choices", "ISO 27001 & SOC 2 Type II", "Open API platform"],
    highlights: [
      { title: "Truly Cloud-Native", desc: "Built for the cloud, not migrated to it — with all the benefits that brings." },
      { title: "Always-On Reliability", desc: "99.99% uptime SLA backed by financial credits and 24x7 SOC." },
      { title: "Scales With Your Business", desc: "From 100 to 100,000 employees on the same architecture." },
    ],
    faqs: stdFaqs("cloud HRMS software"),
    related: [
      { label: "Enterprise HRMS Software", to: "/enterprise-hrms-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "Workforce Management Software", to: "/workforce-management-software" },
    ],
  }),
  s({
    slug: "enterprise-hrms-software",
    title: "Enterprise HRMS Software",
    metaTitle: "Enterprise HRMS Software — Radix StratEdge",
    metaDescription: "Enterprise-grade HRMS software for 10,000 to 200,000+ employees across entities, geographies and statutory regimes.",
    intro: "Radix StratEdge Enterprise HRMS Software is purpose-built for organisations operating at scale — 10,000 to 200,000+ employees, multiple legal entities, dozens of countries, hundreds of business units and complex statutory regimes. Where legacy enterprise HR systems demand multi-year implementations and seven-figure customisations, Radix delivers enterprise capability with mid-market speed.",
    body1: "Multi-entity architecture supports unlimited legal entities with isolated policies, approval matrices, payroll calendars, statutory codes and reporting — all from a single tenant. Multi-country payroll covers 50+ countries with localised tax engines. Global mobility workflows handle visas, transfers, expat payroll, shadow payroll and tax equalisation. Multi-currency support, IFRS-compliant journals and SOX-grade controls satisfy the most demanding finance and audit requirements.",
    body2: "Governance is first-class — role-based access with field-level masking, segregation of duties, configurable approval matrices, immutable audit trails and SOC 2 Type II controls. Dedicated CSMs, named technical account managers, enterprise SLAs and 24x7 priority support ensure Radix scales with your business. The platform's metadata-driven architecture means enterprise customisation doesn't require code — administrators can configure objects, fields, workflows, dashboards and reports in a no-code studio that respects every governance control.",
    bullets: ["Unlimited multi-entity support", "50+ country payroll", "Global mobility workflows", "SOC 2 Type II controls", "Dedicated CSM & 24x7 support", "No-code enterprise configuration"],
    highlights: [
      { title: "Built for 100,000+ Employees", desc: "Customers run Radix at 200,000-employee scale with sub-second response." },
      { title: "Multi-Entity, Multi-Country", desc: "Unlimited entities, 50+ countries, full global mobility — out of the box." },
      { title: "Enterprise Governance", desc: "RBAC, field-level masking, audit trails and SOX-grade controls." },
    ],
    faqs: stdFaqs("enterprise HRMS software"),
    related: [
      { label: "Cloud HRMS Software", to: "/cloud-hrms-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "Workforce Management Software", to: "/workforce-management-software" },
    ],
  }),
  s({
    slug: "ai-powered-hr-software",
    title: "AI-Powered HR Software",
    metaTitle: "AI-Powered HR Software — Radix StratEdge",
    metaDescription: "AI-powered HR software with conversational HR assistant, attrition prediction, resume screening and smart insights.",
    intro: "Radix StratEdge AI HR Software embeds production-grade AI into every step of the employee lifecycle — from resume screening to attrition prediction to a conversational HR assistant employees actually love. Unlike point AI tools bolted onto legacy systems, Radix AI is native to the platform, governed end-to-end and explainable by design.",
    body1: "On the talent side, AI parses resumes with 95%+ accuracy, ranks candidates against requisitions with explainable scoring, drafts job descriptions and outreach messages, summarises interview feedback and surfaces diversity considerations. In performance management, AI summarises 360° feedback, detects bias in calibration and recommends growth actions. In learning, AI recommends courses based on role, skill gaps and career goals. In analytics, AI predicts attrition with explainable drivers, scores engagement and surfaces pay-equity gaps.",
    body2: "The conversational HR assistant — available in chat, Slack, Teams and WhatsApp — answers policy questions, generates letters, summarises payslips and walks employees through self-service flows in natural language across English, Hindi and 20+ languages. The assistant is trained on your company policies, handbook and SOPs with strict role-based access controls. Every AI feature is governed — explainability is mandatory, data residency is respected, no cross-tenant training happens, and admins can disable any AI feature at any time.",
    bullets: ["Conversational HR assistant in 20+ languages", "Attrition prediction with explainable drivers", "AI resume parsing & screening", "Bias detection in performance reviews", "AI learning recommendations", "Pay-equity analytics"],
    highlights: [
      { title: "AI That's Native, Not Bolted-On", desc: "Embedded in every workflow — not a separate add-on with integration drama." },
      { title: "Explainable by Design", desc: "Every prediction defensible — no black-box outputs that HR can't justify." },
      { title: "Governed and Safe", desc: "No cross-tenant training, strict data residency, admin controls everywhere." },
    ],
    faqs: stdFaqs("AI HR software"),
    related: [
      { label: "People Analytics Software", to: "/people-analytics-software" },
      { label: "HR Analytics Software", to: "/hr-analytics-software" },
      { label: "Applicant Tracking System", to: "/applicant-tracking-system" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "manufacturing-hrms",
    title: "HRMS for Manufacturing",
    metaTitle: "Manufacturing HRMS Software — Radix StratEdge",
    metaDescription: "HRMS for manufacturing with shift rosters, contract labour, biometric attendance and statutory compliance across plants.",
    intro: "Radix StratEdge HRMS for Manufacturing unifies plant workforce management across shifts, contract labour, statutory compliance and shop-floor productivity. Trusted by leading auto, FMCG, pharma, chemicals and engineering manufacturers, Radix scales from single facilities to networks of plants across geographies.",
    body1: "Smart shift rosters respect union rules, statutory rest periods and skill requirements — built in minutes by a constraint-based engine. Biometric and RFID integrations cover 50+ device brands across face, fingerprint and gate-level RFID, with shift-aware overtime, comp-off and statutory calculations. The Contract Labour module handles the full contractor lifecycle with statutory compliance reports for Contract Labour Act, PF, ESI, PT, LWF and bespoke client formats — ready for inspection without manual prep.",
    body2: "Plant payroll handles daily-wage, piece-rate and salary employees in a single engine. Productivity dashboards link attendance to output, OEE and cost-per-unit — turning HR data into operational insight that operations leaders actually use. The platform's mobile-first ESS works in low-data environments and supports 20+ Indian languages, ideal for plant workers across India. Implementation timelines for multi-plant rollouts typically run 8–12 weeks with our manufacturing-experienced team.",
    bullets: ["Multi-plant shift rostering", "Contract labour lifecycle", "Biometric & RFID at gates", "Daily-wage & piece-rate payroll", "Statutory compliance automation", "Productivity dashboards"],
    highlights: [
      { title: "Made for the Shop Floor", desc: "Shift, contract labour and statutory complexity — handled natively." },
      { title: "Productivity Visibility", desc: "Link attendance to output, OEE and cost-per-unit." },
      { title: "Inspection-Ready Compliance", desc: "Statutory reports always ready — no end-of-month panic." },
    ],
    faqs: stdFaqs("manufacturing HRMS"),
    related: [
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "Construction HRMS", to: "/construction-hrms" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "construction-hrms",
    title: "HRMS for Construction",
    metaTitle: "Construction HRMS Software — Radix StratEdge",
    metaDescription: "Construction HRMS with site geo-attendance, daily-wage payroll, contractor compliance and safety management.",
    intro: "Radix StratEdge HRMS for Construction is the mobile-first, geo-fenced workforce platform purpose-built for the realities of construction — workforce changing daily, remote sites, sprawling contractors and high statutory exposure. From road builders to infra majors to residential developers, Radix delivers real-time site visibility without slowing operations.",
    body1: "Geo-fenced site attendance with selfie verification eliminates ghost workers and gives real-time site headcount. The mobile app works offline with tamper-evident local storage and syncs when connectivity returns. The daily-wage engine settles workers on daily, weekly or monthly cycles with statutory deductions (PF, ESI, PT, LWF), bank file generation and full audit trails. Contractor compliance covers the full lifecycle — onboarding, statutory reports, billing and exit — for Contract Labour Act and state-specific requirements.",
    body2: "The safety module tracks PPE issuance, safety training, toolbox talks and incident reporting — building a measurable safety culture on every site. Pre-built dashboards show real-time headcount per site, productivity by labour type, contractor performance and safety metrics. The platform supports 20+ Indian languages with voice-driven input for workers with low literacy. Implementation timelines typically run 6–10 weeks for multi-site rollouts.",
    bullets: ["Geo-fenced site attendance", "Daily-wage payroll engine", "Contractor compliance lifecycle", "Safety & PPE tracking", "Offline mobile app", "20+ Indian languages"],
    highlights: [
      { title: "Real-Time Site Visibility", desc: "Live headcount and productivity across every site, every day." },
      { title: "Daily Settlement Automation", desc: "Daily, weekly or monthly wage settlement with statutory compliance." },
      { title: "Safety Culture Built In", desc: "PPE, training and incident reporting on the site supervisor's mobile." },
    ],
    faqs: stdFaqs("construction HRMS"),
    related: [
      { label: "Manufacturing HRMS", to: "/manufacturing-hrms" },
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "healthcare-hrms",
    title: "HRMS for Healthcare",
    metaTitle: "Healthcare HRMS Software — Radix StratEdge",
    metaDescription: "Healthcare HRMS for nurse rostering, credential tracking, HIPAA-ready data and 24x7 shift operations.",
    intro: "Radix StratEdge HRMS for Healthcare is the workforce platform purpose-built for hospitals, healthcare networks, diagnostic chains and clinical research organisations. From nurse rostering to credential tracking to HIPAA-grade controls, Radix handles the unique demands of 24x7 clinical operations.",
    body1: "The nurse rostering engine balances skill, ward, certification, patient load and statutory rest to build compliant rosters in minutes. Credential tracking covers every licence, certification and renewal for clinicians with auto-alerts that prevent costly lapses. HIPAA-aligned data controls — encryption, audit, RBAC and field-level masking — protect employees, clinicians and patient-linked data. Engagement workflows — pulse surveys, manager 1:1s, attrition predictions — help reduce the 25%+ annual nurse turnover that plagues the industry.",
    body2: "The platform integrates with HIS/EMR systems via APIs and HL7 connectors, eliminating duplicate data entry for clinical staff. Multi-location architecture supports hospital networks with centralised governance and local autonomy. Mobile-first ESS works for clinicians on the move, with shift swaps, leave application and credential renewals available from any device. Implementation timelines for multi-hospital rollouts typically run 10–14 weeks with our healthcare-experienced implementation team.",
    bullets: ["Skill-aware nurse rostering", "Credential & licence tracking", "HIPAA-ready controls", "HIS/EMR integration", "Attrition AI for clinicians", "Mobile shift swaps"],
    highlights: [
      { title: "Built for 24x7 Healthcare", desc: "Shift, skill, credential and patient-load complexity handled natively." },
      { title: "HIPAA-Aligned Controls", desc: "Encryption, audit and access controls meet healthcare's data demands." },
      { title: "Reduce Clinician Attrition", desc: "Engagement, pulse and attrition AI tackle the 25% nurse turnover problem." },
    ],
    faqs: stdFaqs("healthcare HRMS"),
    related: [
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
      { label: "People Analytics Software", to: "/people-analytics-software" },
    ],
  }),
  s({
    slug: "retail-hrms",
    title: "HRMS for Retail",
    metaTitle: "Retail HRMS Software — Radix StratEdge",
    metaDescription: "Retail HRMS for store associate rostering, bulk hiring, incentives and mobile self-service across hundreds of outlets.",
    intro: "Radix StratEdge HRMS for Retail is the workforce platform built for the speed and scale of retail and QSR operations — hundreds of stores, thousands of associates, high turnover, peak seasons and complex incentive structures. From national chains to fast-growing D2C retailers, Radix runs the people side of retail at the speed of the store floor.",
    body1: "Demand-driven store rostering optimises shift coverage with swaps, open shifts and store-level flexibility. The bulk hiring engine processes 10,000+ applications per cycle with assessments, group offers and 24-hour onboarding — perfect for festive and seasonal peaks. The incentives module handles store, role, SKU and target-based incentive structures with auto-calculation and direct payroll handoff. Disputes drop by 80%+ because every calculation is transparent and auditable.",
    body2: "A mobile-first ESS app — designed for low-data environments and 20+ Indian languages — keeps the frontline informed, learning and engaged. Push notifications keep store associates aware of payslips, leave approvals, learning deadlines and store-level news. Real-time dashboards show store-level coverage, attendance, incentive payouts and learning completion. The platform integrates with leading POS, workforce planning and finance systems — eliminating duplicate data entry and giving store operations a single source of workforce truth.",
    bullets: ["Demand-driven store rostering", "Bulk hiring with 24h onboarding", "Configurable incentives engine", "Low-data mobile ESS", "Multi-language frontline app", "POS & finance integration"],
    highlights: [
      { title: "Built for Store Floors", desc: "Low-data mobile app, vernacular UI, push-driven engagement for frontline." },
      { title: "Bulk Hiring at Peak Speed", desc: "Hire 5,000 associates in 3 weeks for festive peaks." },
      { title: "Accurate Incentive Payouts", desc: "Configurable engine eliminates 80%+ of incentive disputes." },
    ],
    faqs: stdFaqs("retail HRMS"),
    related: [
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "Applicant Tracking System", to: "/applicant-tracking-system" },
      { label: "Payroll Software India", to: "/payroll-software-india" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "staffing-agency-hrms",
    title: "HRMS for Staffing Agencies",
    metaTitle: "Staffing Agency HRMS Software — Radix StratEdge",
    metaDescription: "Staffing HRMS for contract workforce, multi-client billing, statutory compliance and recruiter productivity at scale.",
    intro: "Radix StratEdge HRMS for Staffing Agencies is purpose-built for the staffing business model — contract workforce management, multi-client billing, end-to-end statutory compliance and high-volume recruiter productivity all on one platform. Customers run 200,000+ contract workers across hundreds of clients on Radix today.",
    body1: "The contract workforce module handles onboarding, deployment, attendance, payroll, billing and exit for tens of thousands of contract workers across hundreds of clients. Multi-client billing supports diverse models — mark-up, mark-down, per-head, fixed-fee — with statutory add-backs (PF, ESI, PT, LWF, bonus, gratuity), margin calculation and automated invoicing in client formats. The compliance engine handles multi-state statutory filings with client-wise reporting ready for inspection.",
    body2: "A recruiter cockpit with bulk hiring, candidate pipelining, vendor portals and recruiter analytics drives the productivity that staffing firms live or die by. AI resume parsing, screening and matching let small recruiter teams handle large requisition volumes. Mobile-first ESS works for contract workers across India with vernacular UI and low-data optimisation. Implementation timelines for large staffing rollouts typically run 8–12 weeks with our staffing-experienced implementation team.",
    bullets: ["Contract workforce at scale", "Multi-client billing models", "Statutory compliance per client", "Bulk hiring & recruiter analytics", "Vernacular mobile ESS", "Integration with client systems"],
    highlights: [
      { title: "Proven at 200,000+ Workers", desc: "Run by top-3 Indian staffing firms — proven at the largest scale." },
      { title: "Multi-Client Billing Built In", desc: "Diverse billing models with statutory add-backs and auto-invoicing." },
      { title: "Recruiter Productivity at Scale", desc: "AI screening and bulk hiring drive the productivity staffing demands." },
    ],
    faqs: stdFaqs("staffing agency HRMS"),
    related: [
      { label: "Applicant Tracking System", to: "/applicant-tracking-system" },
      { label: "Payroll Software India", to: "/payroll-software-india" },
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
    ],
  }),
  s({
    slug: "logistics-hrms",
    title: "HRMS for Logistics",
    metaTitle: "Logistics HRMS Software — Radix StratEdge",
    metaDescription: "Logistics HRMS for driver attendance, hub workforce, route adherence and multi-state statutory compliance.",
    intro: "Radix StratEdge HRMS for Logistics is the mobile-first, geo-aware workforce platform for logistics, supply chain and last-mile delivery operations. From driver attendance to hub workforce to multi-state statutory compliance, Radix delivers real-time visibility across every node of your network.",
    body1: "Driver and hub attendance is captured with geo-fenced selfie verification, offline support and tamper-evident hashing — eliminating ghost workers across hundreds of hubs. Live route tracking shows driver location, stops, dwell times and exceptions without draining batteries. Multi-state payroll handles PT, LWF, Motor Transport Workers Act and contract labour compliance — critical for logistics operations spanning dozens of states.",
    body2: "Engagement workflows — pulse surveys, recognition, attrition AI — help reduce the 30%+ annual driver attrition that plagues the industry, with measurable cost savings. The platform integrates bidirectionally with leading TMS, WMS and ERP systems for route, stop, driver assignment and finance data flow. Mobile-first ESS works for drivers in low-data, low-spec device environments with vernacular UI across 20+ Indian languages.",
    bullets: ["Geo-fenced hub & driver attendance", "Battery-efficient live tracking", "Multi-state statutory compliance", "Driver attrition AI", "TMS & WMS integration", "Vernacular mobile ESS"],
    highlights: [
      { title: "Real-Time Hub Visibility", desc: "Live headcount and exceptions across 200+ hubs." },
      { title: "Battery-Efficient Tracking", desc: "Live driver tracking with <3% daily battery impact." },
      { title: "Reduce Driver Attrition", desc: "Engagement and attrition AI tackle the 30% driver turnover problem." },
    ],
    faqs: stdFaqs("logistics HRMS"),
    related: [
      { label: "Workforce Management Software", to: "/workforce-management-software" },
      { label: "Attendance Management Software", to: "/attendance-management-software" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
  s({
    slug: "education-hrms",
    title: "HRMS for Education",
    metaTitle: "Education HRMS Software — Radix StratEdge",
    metaDescription: "Education HRMS for faculty management, academic workflows, attendance and statutory compliance.",
    intro: "Radix StratEdge HRMS for Education is the workforce platform purpose-built for schools, universities, colleges and EdTech operators. From full-time faculty to guest lecturers, semester-based workflows to UGC and AICTE compliance, Radix understands the unique rhythm of educational institutions.",
    body1: "The faculty module supports every employment type — full-time, part-time, guest, visiting, adjunct — with bespoke compensation, term structures and statutory treatments. Academic workflows align with the semester calendar — rosters, evaluations, workload distribution, leave entitlements and payroll cycles all respect academic timelines. The compliance engine handles UGC, AICTE, state-board and school-board reporting alongside standard statutory filings (PF, ESI, PT, Bonus Act, Gratuity).",
    body2: "Engagement tools — pulse surveys, recognition, peer learning, faculty development — keep faculty motivated and the campus thriving. Mobile-first ESS makes self-service available to faculty and admin staff alike. The Radix LMS is natively integrated, so faculty development, mandatory training and certifications are tracked in the same system as employment data. Implementation timelines for multi-campus rollouts typically run 8–12 weeks.",
    bullets: ["Multi-type faculty management", "Semester-aligned workflows", "UGC/AICTE reporting", "Native LMS integration", "Mobile ESS for faculty", "Multi-campus governance"],
    highlights: [
      { title: "Built for Academic Calendars", desc: "Semester-based workflows that respect how education actually runs." },
      { title: "Regulatory Reporting", desc: "UGC, AICTE, state-board reporting alongside statutory filings." },
      { title: "Faculty Engagement", desc: "Pulse, recognition and development drive faculty satisfaction." },
    ],
    faqs: stdFaqs("education HRMS"),
    related: [
      { label: "Learning Management System", to: "/learning-management-system" },
      { label: "HRMS Software India", to: "/hrms-software-india" },
      { label: "Payroll Software India", to: "/payroll-software-india" },
      { label: "AI HR Software", to: "/ai-powered-hr-software" },
    ],
  }),
];

export const seoMap: Record<string, SeoContent> = Object.fromEntries(seoPages.map((p) => [p.slug, p]));
